
import React from 'react';

export const TOKENS = {
  colors: {
    primary: {
      50: '#eff6ff',
      100: '#dbeafe',
      200: '#bfdbfe',
      500: '#3b82f6',
      600: '#2563eb',
      700: '#1d4ed8',
      900: '#1e3a8a',
    },
    neutral: {
      50: '#f8fafc',
      100: '#f1f5f9',
      200: '#e2e8f0',
      300: '#cbd5e1',
      600: '#475569',
      900: '#0f172a',
    },
    success: '#10b981',
    error: '#ef4444',
    warning: '#f59e0b',
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
  },
  radius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '24px',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1)',
  }
};

export const ICONS = {
  Home: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>,
  Cases: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 2H2v10c0 1.1.9 2 2 2h12a2 2 0 0 0 2-2V7l-5-5Z"/><path d="M2 10h12"/><path d="M12 2v5h5"/><path d="M22 6v14a2 2 0 0 1-2 2H7"/><path d="M18 14h4"/></svg>,
  Credits: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="10"/><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/><path d="M12 18V6"/></svg>,
  Settings: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.1a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/></svg>,
  Translate: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m5 8 6 6"/><path d="m4 14 6-6 2-3"/><path d="M2 5h12"/><path d="M7 2h1"/><path d="m22 22-5-10-5 10"/><path d="M14 18h6"/></svg>,
  ChevronRight: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m9 18 6-6-6-6"/></svg>,
  Plus: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 5v14M5 12h14"/></svg>,
  Check: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M20 6 9 17l-5-5"/></svg>,
  X: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>,
  Paperclip: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l8.57-8.57A4 4 0 1 1 18 8.84l-8.59 8.57a2 2 0 0 1-2.83-2.83l8.49-8.48"/></svg>,
  File: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/></svg>,
  Folder: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/></svg>,
  Camera: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z"/><circle cx="12" cy="13" r="3"/></svg>,
  Globe: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/></svg>,
  Shield: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>,
};

export const UI_TRANSLATIONS: Record<string, any> = {
  nl: { 
    label: "Nederlands", 
    tagline: "Conflict oplossen,", 
    tagline_highlight: "zonder gedoe.",
    sub_tagline: "Bereik samen een eerlijke oplossing met hulp van AI mediation.",
    start_btn: "Start Mediation (€3,99)",
    invited_btn: "Ik ben uitgenodigd",
    dossier: "Bewijs Dossier", 
    items_collected: "items verzameld", 
    no_evidence: "Nog geen bewijsmateriaal geüpload.", 
    view_download: "Bekijken / Download", 
    online: "is online", 
    waiting: "Wachten op", 
    placeholder: "Schrijf een bericht...", 
    settings: "Taalinstellingen", 
    app_lang: "App Taal", 
    close: "Sluiten", 
    dossier_status: "Dossier Status", 
    invitation_sent: "Link is verstuurd naar {name}.", 
    mediator: "Mediator", 
    you: "Jij", 
    system: "Systeem",
    payment_title: "Eénmalige Betaling",
    pay_btn: "Betaal €3,99",
    choosing_bank: "Kies je bank...",
    legal_vso: "Rechtsgeldige VSO door AI",
    disclaimer_title: "Belangrijke Informatie",
    disclaimer_body: "Rsolve is een AI-hulp bij conflictbemiddeling. Belangrijk: Deze app geeft GEEN juridisch advies en vervangt geen advocaat. Wij helpen je op praktische wijze om samen tot een eerlijke oplossing te komen.",
    disclaimer_agree: "Ik begrijp het en ga akkoord"
  },
  en: { 
    label: "English", 
    tagline: "Resolve conflict,", 
    tagline_highlight: "without the hassle.",
    sub_tagline: "Reach a fair solution together with the help of AI mediation.",
    start_btn: "Start Mediation (€3.99)",
    invited_btn: "I have been invited",
    dossier: "Evidence File", 
    items_collected: "items collected", 
    no_evidence: "No evidence uploaded yet.", 
    view_download: "View / Download", 
    online: "is online", 
    waiting: "Waiting for", 
    placeholder: "Write a message...", 
    settings: "Language Settings", 
    app_lang: "App Language", 
    close: "Close", 
    dossier_status: "Case Status", 
    invitation_sent: "Link sent to {name}.", 
    mediator: "Mediator", 
    you: "You", 
    system: "System",
    payment_title: "One-time Payment",
    pay_btn: "Pay €3.99",
    choosing_bank: "Choose your bank...",
    legal_vso: "Legally binding VSO by AI",
    disclaimer_title: "Important Notice",
    disclaimer_body: "Rsolve is an AI assistant for conflict resolution. Important: This app does NOT provide legal advice and does not replace a lawyer. We help you in a practical way to reach a fair solution together.",
    disclaimer_agree: "I understand and agree"
  },
  tr: { 
    label: "Türkçe", 
    tagline: "Anlaşmazlığı çözün,", 
    tagline_highlight: "zahmetsizce.",
    sub_tagline: "AI arabuluculuğu yardımıyla birlikte adil bir çözüme ulaşın.",
    start_btn: "Arabuluculuğu Başlat (€3,99)",
    invited_btn: "Davet edildim",
    dossier: "Kanıt Dosyası", 
    items_collected: "öğe toplandı", 
    no_evidence: "Henüz kanıt yüklenmedi.", 
    view_download: "Görüntüle / İndir", 
    online: "çevrimiçi", 
    waiting: "Bekleniyor:", 
    placeholder: "Bir mesaj yazın...", 
    settings: "Dil Ayarları", 
    app_lang: "Uygulama Dili", 
    close: "Kapat", 
    dossier_status: "Dosya Durumu", 
    invitation_sent: "Bağlantı {name} kişisine gönderildi.", 
    mediator: "Arabulucu", 
    you: "Sen", 
    system: "Sistem",
    payment_title: "Tek Seferlik Ödeme",
    pay_btn: "Öde €3,99",
    choosing_bank: "Bankanızı seçin...",
    legal_vso: "Yapay Zeka ile Yasal VSO",
    disclaimer_title: "Önemli Bilgi",
    disclaimer_body: "Rsolve, yapay zeka destekli bir arabuluculuk aracıdır. Önemli: Bu uygulama yasal danışmanlık VERMEZ ve bir avukatın yerini tutmaz. Pratik bir şekilde adil bir çözüme ulaşmanıza yardımcı oluruz.",
    disclaimer_agree: "Anladım ve kabul ediyorum"
  },
  ar: { 
    label: "العربية", 
    tagline: "حل النزاع،", 
    tagline_highlight: "دون عناء.",
    sub_tagline: "توصلوا إلى حل عادل معًا بمساعدة وساطة الذكاء الاصطناعي.",
    start_btn: "بدء الوساطة (3.99 يورو)",
    invited_btn: "لقد تمت دعوتي",
    dossier: "ملف الأدلة", 
    items_collected: "تم جمع العناصر", 
    no_evidence: "لم يتم تحميل أي أدلة بعد.", 
    view_download: "عرض / تحميل", 
    online: "متصل", 
    waiting: "في انتظار", 
    placeholder: "اكتب رسالة...", 
    settings: "إعدادات اللغة", 
    app_lang: "لغة التطبيق", 
    close: "إغلاق", 
    dossier_status: "حالة القضية", 
    invitation_sent: "تم إرسال الرابط إلى {name}.", 
    mediator: "الوسيط", 
    you: "أنت", 
    system: "النظام",
    payment_title: "دفع لمرة واحدة",
    pay_btn: "دفع 3.99 يورو",
    choosing_bank: "اختر بنكك...",
    legal_vso: "اتفاقية قانونية بواسطة الذكاء الاصطناعي",
    disclaimer_title: "معلومات هامة",
    disclaimer_body: "Rsolve هي أداة للمساعدة في حل النزاعات بالذكاء الاصطناعي. هام: هذا التطبيق لا يقدم نصائح قانونية ولا يغني عن المحامي. نحن نساعدك بطريقة عملية للوصول إلى حل عادل معًا.",
    disclaimer_agree: "أفهم وأوافق"
  },
  es: { label: "Español", tagline: "Resuelve conflictos,", tagline_highlight: "sin líos.", start_btn: "Iniciar Mediación (€3,99)", invited_btn: "He sido invitado", dossier: "Expediente de Pruebas", items_collected: "elementos recogidos", no_evidence: "Aún no se han subido pruebas.", view_download: "Ver / Descargar", online: "en línea", waiting: "Esperando a", placeholder: "Escribe un mensaje...", settings: "Ajustes de Idioma", app_lang: "Idioma de la App", close: "Cerrar", dossier_status: "Estado del Caso", invitation_sent: "Enlace enviado a {name}.", mediator: "Mediador", you: "Tú", system: "Sistema", payment_title: "Pago Único", pay_btn: "Pagar €3,99", choosing_bank: "Elige tu banco...", disclaimer_title: "Información Importante", disclaimer_body: "Rsolve es una ayuda de IA para la resolución de conflictos. Importante: Esta aplicación NO proporciona asesoramiento legal y no reemplaza a un abogado.", disclaimer_agree: "Entiendo y acepto" },
  fr: { label: "Français", tagline: "Résolvez les conflits,", tagline_highlight: "sans tracas.", start_btn: "Démarrer la médiation (3,99 €)", invited_btn: "J'ai été invité", dossier: "Dossier de Preuves", items_collected: "éléments collectés", no_evidence: "Aucune preuve téléchargée.", view_download: "Voir / Télécharger", online: "en ligne", waiting: "En attente de", placeholder: "Écrire un message...", settings: "Langue", app_lang: "Langue de l'app", close: "Fermer", dossier_status: "Statut du Dossier", invitation_sent: "Lien envoyé à {name}.", mediator: "Médiateur", you: "Vous", system: "Système", payment_title: "Paiement Unique", pay_btn: "Payer 3,99 €", choosing_bank: "Choisissez votre banque...", disclaimer_title: "Information Importante", disclaimer_body: "Rsolve est une aide IA pour la résolution de conflits. Important : Cette application ne fournit PAS de conseils juridiques et ne remplace pas un avocat.", disclaimer_agree: "Je comprends et j'accepte" },
  de: { label: "Deutsch", tagline: "Konflikte lösen,", tagline_highlight: "ohne Stress.", start_btn: "Mediation starten (€3,99)", invited_btn: "Ich wurde eingeladen", dossier: "Beweisakte", items_collected: "Elemente gesammelt", no_evidence: "Noch keine Beweise hochgeladen.", view_download: "Ansehen / Download", online: "ist online", waiting: "Warten auf", placeholder: "Nachricht schreiben...", settings: "Sprache", app_lang: "App-Sprache", close: "Schließen", dossier_status: "Fallstatus", invitation_sent: "Link an {name} gesendet.", mediator: "Mediator", you: "Du", system: "System", payment_title: "Einmalige Zahlung", pay_btn: "Bezahlen €3,99", choosing_bank: "Wählen Sie Ihre Bank...", disclaimer_title: "Wichtiger Hinweis", disclaimer_body: "Rsolve ist ein KI-gestütztes Tool zur Konfliktlösung. Wichtig: Diese App bietet KEINE Rechtsberatung und ersetzt keinen Anwalt.", disclaimer_agree: "Ich verstehe und stimme zu" },
  pl: { label: "Polski", tagline: "Rozwiązuj konflikty,", tagline_highlight: "bez problemów.", start_btn: "Rozpocznij mediację (3,99 €)", invited_btn: "Zostałem zaproszony", dossier: "Akta Dowodowe", items_collected: "elementy zebrane", no_evidence: "Nie przesłano jeszcze dowodów.", view_download: "Zobacz / Pobierz", online: "jest online", waiting: "Oczekiwanie na", placeholder: "Napisz wiadomość...", settings: "Język", app_lang: "Język aplikacji", close: "Zamknij", dossier_status: "Status Sprawy", invitation_sent: "Link wysłany do {name}.", mediator: "Mediator", you: "Ty", system: "System", payment_title: "Płatność Jednorazowa", pay_btn: "Zapłać 3,99 €", choosing_bank: "Wybierz swój bank...", disclaimer_title: "Ważna Informacja", disclaimer_body: "Rsolve to pomoc AI w mediacji. Ważne: Ta aplikacja NIE udziela porad prawnych i nie zastępuje prawnika.", disclaimer_agree: "Rozumiem i akceptuję" },
  ua: { label: "Українська", tagline: "Вирішуйте конфлікти,", tagline_highlight: "без клопоту.", start_btn: "Почати медіацію (3,99 €)", invited_btn: "Мене запросили", dossier: "Досьє доказів", items_collected: "елементів зібрано", no_evidence: "Докази ще не завантажені.", view_download: "Переглянути / Завантажити", online: "в мережі", waiting: "Очікування на", placeholder: "Напишіть повідомлення...", settings: "Мова", app_lang: "Мова додатка", close: "Закрити", dossier_status: "Статус справи", invitation_sent: "Посилання надіслано {name}.", mediator: "Медіатор", you: "Ви", system: "Система", payment_title: "Одноразовий платіж", pay_btn: "Оплатити 3,99 €", choosing_bank: "Виберіть свій банк...", disclaimer_title: "Важлива інформація", disclaimer_body: "Rsolve — це допомога ШІ у вирішенні конфліктів. Важливо: ця програма НЕ надає юридичних консультацій і не замінює юриста.", disclaimer_agree: "Я розумію та погоджуюся" },
  it: { label: "Italiano", tagline: "Risolvi i conflitti,", tagline_highlight: "senza stress.", start_btn: "Inizia Mediazione (€3,99)", invited_btn: "Sono stato invitato", dossier: "Fascicolo Prove", items_collected: "elementi raccolti", no_evidence: "Nessuna prova ancora caricata.", view_download: "Visualizza / Scarica", online: "è online", waiting: "In attesa di", placeholder: "Scrivi un messaggio...", settings: "Lingua", app_lang: "Lingua App", close: "Chiudi", dossier_status: "Stato del Caso", invitation_sent: "Link inviato a {name}.", mediator: "Mediatore", you: "Tu", system: "Sistema", payment_title: "Pagamento Una Tantum", pay_btn: "Paga €3,99", choosing_bank: "Scegli la tua banca...", disclaimer_title: "Informazioni Importanti", disclaimer_body: "Rsolve è un supporto AI per la mediazione dei conflitti. Importante: Questa app NON fornisce consulenza legale e non sostituisce un avvocato.", disclaimer_agree: "Capisco e accetto" },
  pt: { label: "Português", tagline: "Resolva conflitos,", tagline_highlight: "sem complicações.", start_btn: "Iniciar Mediação (€3,99)", invited_btn: "Fui convidado", dossier: "Dossiê de Provas", items_collected: "itens recolhidos", no_evidence: "Nenhuma prova enviada ainda.", view_download: "Ver / Download", online: "está online", waiting: "Aguardando", placeholder: "Escreva uma mensagem...", settings: "Idioma", app_lang: "Idioma da App", close: "Fechar", dossier_status: "Status do Caso", invitation_sent: "Link enviado para {name}.", mediator: "Mediador", you: "Você", system: "Sistema", payment_title: "Pagamento Único", pay_btn: "Pagar €3,99", choosing_bank: "Escolha o seu banco...", disclaimer_title: "Informação Importante", disclaimer_body: "O Rsolve é uma ajuda de IA para a resolução de conflitos. Importante: Esta aplicação NÃO fornece aconselhamento jurídico e não substitui um advogado.", disclaimer_agree: "Compreendo e aceito" },
  ro: { label: "Română", tagline: "Rezolvă conflictele,", tagline_highlight: "fără bătăi de cap.", start_btn: "Începe medierea (3,99 €)", invited_btn: "Am fost invitat", dossier: "Dosar de Probe", items_collected: "elemente colectate", no_evidence: "Nu s-au încărcat încă probe.", view_download: "Vezi / Descarcă", online: "este online", waiting: "Se așteaptă", placeholder: "Scrie un mesaj...", settings: "Limbă", app_lang: "Limba Aplicației", close: "Închide", dossier_status: "Status Caz", invitation_sent: "Link trimis către {name}.", mediator: "Mediator", you: "Tu", system: "Sistem", payment_title: "Plată Unică", pay_btn: "Plătește 3,99 €", choosing_bank: "Alege banca ta...", disclaimer_title: "Informații Importante", disclaimer_body: "Rsolve este un ajutor AI pentru rezolvarea conflictelor. Important: Această aplicație NU oferă consultanță juridică și nu înlocuiește un avocat.", disclaimer_agree: "Înțeleg și sunt de acord" }
};
