
import React from 'react';

export const TOKENS = {
  colors: {
    primary: {
      50: '#eff6ff',
      100: '#dbeafe',
      200: '#bfdbfe',
      500: '#3b82f6',
      600: '#2563eb',
      700: '#1d4ed8',
      900: '#1e3a8a',
    },
    neutral: {
      50: '#f8fafc',
      100: '#f1f5f9',
      200: '#e2e8f0',
      300: '#cbd5e1',
      600: '#475569',
      900: '#0f172a',
    },
    success: '#10b981',
    error: '#ef4444',
    warning: '#f59e0b',
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
  },
  radius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '24px',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1)',
  }
};

export const ICONS = {
  Home: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>,
  Cases: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 2H2v10c0 1.1.9 2 2 2h12a2 2 0 0 0 2-2V7l-5-5Z"/><path d="M2 10h12"/><path d="M12 2v5h5"/><path d="M22 6v14a2 2 0 0 1-2 2H7"/><path d="M18 14h4"/></svg>,
  Credits: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="10"/><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/><path d="M12 18V6"/></svg>,
  Settings: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.1a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/></svg>,
  Translate: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m5 8 6 6"/><path d="m4 14 6-6 2-3"/><path d="M2 5h12"/><path d="M7 2h1"/><path d="m22 22-5-10-5 10"/><path d="M14 18h6"/></svg>,
  ChevronRight: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m9 18 6-6-6-6"/></svg>,
  ChevronDown: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m6 9 6 6 6-6"/></svg>,
  Plus: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 5v14M5 12h14"/></svg>,
  Check: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M20 6 9 17l-5-5"/></svg>,
  X: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>,
  Paperclip: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l8.57-8.57A4 4 0 1 1 18 8.84l-8.59 8.57a2 2 0 0 1-2.83-2.83l8.49-8.48"/></svg>,
  File: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/></svg>,
  Folder: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/></svg>,
  Camera: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z"/><circle cx="12" cy="13" r="3"/></svg>,
  Globe: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/></svg>,
  Shield: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>,
  Zap: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>,
  Clock: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>,
  Handshake: (props: any) => <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="m11 17 2 2a1 1 0 1 0 3-3"/><path d="m9 2 2.5 2.5a2.121 2.121 0 0 1 0 3L7 12l-4-4 2.5-2.5a2.121 2.121 0 0 1 3 0Z"/><path d="M8 22l4-4 6 6 4-4-6-6-4 4 6 6"/><path d="m17 7 2.5-2.5a2.121 2.121 0 1 1 3 3L20 10"/></svg>,
};

type TranslationKey = 
  | 'label' | 'tagline' | 'tagline_highlight' | 'sub_tagline' | 'start_btn' | 'invited_btn'
  | 'micro_time' | 'section_not_winning_title' | 'section_not_winning_text'
  | 'what_is_title' | 'what_is_p1' | 'what_is_list_1' | 'what_is_list_2' | 'what_is_list_3' | 'what_is_list_4'
  | 'language_title' | 'language_text' | 'when_title' | 'when_text' | 'why_title'
  | 'why_1' | 'why_2' | 'why_3' | 'why_4' | 'why_5' | 'why_6'
  | 'how_title' | 'how_step_1' | 'how_step_2' | 'how_step_3' | 'how_step_4'
  | 'faq_title' | 'faq_1_q' | 'faq_1_a' | 'faq_2_q' | 'faq_2_a' | 'faq_3_q' | 'faq_3_a' | 'faq_4_q' | 'faq_4_a' | 'faq_5_q' | 'faq_5_a'
  | 'footer_payoff' | 'footer_expats'
  | 'dossier' | 'items_collected' | 'no_evidence' | 'view_download' | 'online' | 'waiting'
  | 'placeholder' | 'settings' | 'app_lang' | 'close' | 'dossier_status' | 'invitation_sent'
  | 'mediator' | 'you' | 'system' | 'payment_title' | 'pay_btn' | 'choosing_bank'
  | 'legal_vso' | 'disclaimer_title' | 'disclaimer_body' | 'disclaimer_agree'
  | 'nav_what_is' | 'nav_start' | 'back_home' | 'payment_desc' | 'secure_trans' | 'pay_via_ideal'
  | 'have_code' | 'enter_code' | 'validate_code' | 'validating' | 'code_placeholder' | 'code_instruction'
  | 'payment_received' | 'lets_start' | 'label_your_name' | 'label_subject' | 'label_counterparty'
  | 'btn_save_invite' | 'invite_header' | 'invite_desc' | 'whatsapp_btn' | 'copy' | 'copied'
  | 'start_mediation_btn' | 'invited_header' | 'join_btn' | 'join_free_notice'
  | 'leave_modal_title' | 'leave_modal_desc' | 'leave_confirm' | 'leave_cancel' | 'leave_btn_label' | 'leave_legal_warning'
  | 'vso_modal_title' | 'vso_generating' | 'vso_confirm' | 'finish_btn' | 'leave_btn'
  | 'analysing' | 'vso_title' | 'legal_doc' | 'download_chat' | 'download_pdf' | 'settlement_agreement'
  | 'legal_accord' | 'section_parties' | 'party_a' | 'party_b' | 'section_dispute'
  | 'dispute_desc' | 'section_terms' | 'no_terms' | 'section_final' | 'final_text'
  | 'sign_party_a' | 'digital_sign' | 'ref' | 'date' | 'sign_placeholder' | 'sign_btn'
  | 'sign_party_b' | 'waiting_sign' | 'congrats' | 'signed_desc' | 'download_dossier'
  | 'delete_close' | 'loading' | 'error_generic' | 'dossier_not_found'
  | 'mediation_badge' | 'when_work' | 'when_business' | 'when_neighbors' | 'when_relations' | 'plus_more'
  | 'placeholder_name' | 'placeholder_subject' | 'placeholder_invite' | 'secure_ssl'
  | 'typing_indicator' | 'mediator_thinking'
  // Rsolve Pro (Fase 4) — overdrachtsdossier-wizard
  | 'pro_header_btn' | 'pro_wizard_title' | 'pro_type_intro'
  | 'pro_type_summary_label' | 'pro_type_summary_desc' | 'pro_type_full_label' | 'pro_type_full_desc'
  | 'pro_language_intro' | 'pro_language_label' | 'pro_language_hint'
  | 'pro_review_intro' | 'pro_review_included_title' | 'pro_review_inc_conversation' | 'pro_review_inc_summary'
  | 'pro_review_inc_own_notes' | 'pro_review_inc_hash' | 'pro_review_excluded_title'
  | 'pro_review_exc_other_notes' | 'pro_review_exc_judgment'
  | 'pro_consent_text' | 'pro_consent_checkbox' | 'pro_generate_btn' | 'pro_generating' | 'pro_generating_btn'
  | 'pro_next' | 'pro_back' | 'pro_close' | 'pro_retry'
  | 'pro_error_title' | 'pro_error_text' | 'pro_result_title' | 'pro_result_docnr' | 'pro_result_items' | 'pro_result_hash'
  | 'pro_download_btn' | 'pro_pdf_unavailable'
  | 'pro_upsell_title' | 'pro_upsell_text' | 'pro_upsell_btn';

const BASE_TRANSLATIONS: Record<TranslationKey, string> = {
  label: "English",
  tagline: "Conflict at work or home?",
  tagline_highlight: "Solve it today.",
  sub_tagline: "You speak your language, they speak theirs. Our AI mediator helps you reach a fair solution within 12 minutes.",
  start_btn: "Start Now (€3.99)",
  invited_btn: "I have been invited",
  micro_time: "Average insight within 8–12 minutes",
  section_not_winning_title: "Winning isn't solving",
  section_not_winning_text: "In a fight, nobody wins. Mediation focuses on finding a way forward, preserving relationships, and saving time.",
  what_is_title: "What is Rsolve?",
  what_is_p1: "Rsolve is an automated mediation platform that uses AI to guide you and the other party to an agreement.",
  what_is_list_1: "Neutral guidance",
  what_is_list_2: "Concrete solutions",
  what_is_list_3: "Clear agreements",
  what_is_list_4: "Optional Settlement Agreement (VSO)",
  language_title: "Works in every language",
  language_text: "Don't let language barriers escalate a conflict. Rsolve translates everything instantly between parties.",
  when_title: "Best for...",
  when_text: "Labor disputes, neighbor conflicts, debt issues, and relationship disagreements.",
  why_title: "Why choose Rsolve?",
  why_1: "No expensive lawyers",
  why_2: "No long waiting times",
  why_3: "Results in minutes",
  why_4: "Costs only €3.99",
  why_5: "Safe & Confidential",
  why_6: "Legally usable agreements",
  how_title: "How it works",
  how_step_1: "Start Case",
  how_step_2: "Invite Party",
  how_step_3: "Guided Chat",
  how_step_4: "Agreement",
  faq_title: "Frequently Asked Questions",
  faq_1_q: "Is it legally valid?",
  faq_1_a: "Yes, the resulting VSO (Settlement Agreement) can be legally binding under Dutch law (Art. 7:900 BW).",
  faq_2_q: "Is my data safe?",
  faq_2_a: "We use encryption and do not share your private data with third parties.",
  faq_3_q: "What if they don't respond?",
  faq_3_a: "You only pay once for the case. If the other party doesn't respond, you at least have a record that you tried to resolve it together. After that, legal help is often the only route. Rsolve works with a network of trusted lawyers we can introduce you to — you can make a no-obligation request via the 'Legal help' page.",
  faq_4_q: "Who is Rsolve for?",
  faq_4_a: "Everyone. Employees, employers, neighbors, and partners.",
  faq_5_q: "What if the other party doesn't comply with the settlement agreement?",
  faq_5_a: "A settlement agreement records your arrangements in a legally binding way. If the other party still fails to comply, there is often no other route than going to court, and hiring a lawyer is usually necessary. The good news: in many cases it is precisely the party that breaks the agreement who ends up losing — a signed agreement is strong evidence. That's why putting your arrangements in a settlement agreement is always an important step in the right direction.",
  footer_payoff: "Rsolve. Solving conflict without the hassle.",
  footer_expats: "Suitable for expats and international workers.",
  dossier: "Evidence File",
  items_collected: "items collected",
  no_evidence: "No evidence uploaded yet.",
  view_download: "View / Download",
  online: "is online",
  waiting: "Waiting for",
  placeholder: "Write a message...",
  settings: "Language Settings",
  app_lang: "App Language",
  close: "Close",
  dossier_status: "Case Status",
  invitation_sent: "Link sent.",
  mediator: "Mediator",
  you: "You",
  system: "System",
  payment_title: "One-time Payment",
  pay_btn: "Pay €3.99",
  choosing_bank: "Choose your bank...",
  legal_vso: "Legally binding VSO by AI",
  disclaimer_title: "Important Notice",
  disclaimer_body: "Rsolve is an AI assistant. It does not provide legal advice.",
  disclaimer_agree: "I agree",
  nav_what_is: "What is mediation?",
  nav_start: "Start mediation",
  back_home: "Back to Home",
  payment_desc: "Payment for AI Mediation Case",
  secure_trans: "Secure Transaction",
  pay_via_ideal: "Pay via iDEAL",
  have_code: "Have an access code?",
  enter_code: "Enter Access Code",
  validate_code: "OK",
  validating: "Validating...",
  code_placeholder: "e.g. RS-2024-XXXX",
  code_instruction: "Enter the code received from your employer/insurer.",
  payment_received: "Payment Received!",
  lets_start: "Let's start the case.",
  label_your_name: "Your Name",
  label_subject: "Conflict Subject",
  label_counterparty: "Counterparty Name",
  btn_save_invite: "Save & Create Invite",
  invite_header: "Invite {name}",
  invite_desc: "Share this link via WhatsApp to officially start.",
  whatsapp_btn: "WhatsApp Invitation",
  copy: "Copy",
  copied: "Copied",
  start_mediation_btn: "Start Mediation Chat",
  invited_header: "You are invited",
  join_btn: "Join Conversation",
  join_free_notice: "Free participation for invitees",
  leave_modal_title: "Leave Mediation?",
  leave_modal_desc: "You will not be able to open this case again.",
  leave_confirm: "Yes, leave session",
  leave_cancel: "No, continue",
  leave_btn_label: "Stop",
  leave_legal_warning: "Warning: Refusing to cooperate in mediation may be viewed unfavorably in future legal proceedings.",
  vso_modal_title: "Review Agreement",
  vso_generating: "Drafting Agreement...",
  vso_confirm: "Confirm Agreement",
  finish_btn: "Finish",
  leave_btn: "Leave",
  analysing: "Mediator is analysing...",
  vso_title: "Settlement Agreement",
  legal_doc: "Legal Document",
  download_chat: "Chat Log (.txt)",
  download_pdf: "Download PDF",
  settlement_agreement: "Settlement Agreement",
  legal_accord: "Private Settlement Agreement • Rsolve AI",
  section_parties: "1. The Parties",
  party_a: "Party A",
  party_b: "Partij B",
  section_dispute: "2. The Dispute",
  dispute_desc: "Parties declare to have had a dispute regarding:",
  section_terms: "3. Agreed Terms",
  no_terms: "No terms specified.",
  section_final: "4. Final Discharge & Legal Force",
  final_text: "Upon execution of terms, parties grant each other final discharge. This agreement is binding (Art. 7:900 BW).",
  sign_party_a: "Signature Party A",
  digital_sign: "Digitally Signed via Rsolve",
  ref: "Ref:",
  date: "Date:",
  sign_placeholder: "Type full name",
  sign_btn: "Sign",
  sign_party_b: "Signature Party B",
  waiting_sign: "Waiting for signature...",
  congrats: "Congratulations!",
  signed_desc: "You have signed. Once the other party signs, mediation is closed.",
  download_dossier: "Download Case",
  delete_close: "Delete Case & Close",
  loading: "Loading...",
  error_generic: "Something went wrong.",
  dossier_not_found: "Case not found.",
  mediation_badge: "Mediation 2.0",
  when_work: "Work",
  when_business: "Business",
  when_neighbors: "Neighbors",
  when_relations: "Relationship",
  plus_more: "+15...",
  placeholder_name: "e.g. Mark",
  placeholder_subject: "e.g. Loan repayment",
  placeholder_invite: "Who to invite?",
  secure_ssl: "Secured by Rsolve SSL",
  typing_indicator: "is typing...",
  mediator_thinking: "Mediator is thinking...",
  // Rsolve Pro (Fase 4)
  pro_header_btn: "Pro",
  pro_wizard_title: "Generate handover file",
  pro_type_intro: "Choose which document you want to generate.",
  pro_type_summary_label: "Summary",
  pro_type_summary_desc: "A concise, professional summary of the conflict and the current status. Ideal for a first handover.",
  pro_type_full_label: "Full file",
  pro_type_full_desc: "The summary plus the complete conversation as source material.",
  pro_language_intro: "In which language should the file be written?",
  pro_language_label: "File language",
  pro_language_hint: "The summary is written in this language. Original statements are preserved.",
  pro_review_intro: "This is what will and will not be included in your file.",
  pro_review_included_title: "Included",
  pro_review_inc_conversation: "The shared conversation with the mediator",
  pro_review_inc_summary: "A neutral, AI-generated summary",
  pro_review_inc_own_notes: "Your own confidential notes (if any)",
  pro_review_inc_hash: "An integrity code (SHA-256) and file number",
  pro_review_excluded_title: "Not included",
  pro_review_exc_other_notes: "The other party's confidential notes — never",
  pro_review_exc_judgment: "No legal judgment or verdict",
  pro_consent_text: "The file may contain personal data. It is generated for handover to a professional (lawyer, mediator, HR or insurer) and is not legal advice.",
  pro_consent_checkbox: "I understand this and want to generate the file for my own use.",
  pro_generate_btn: "Generate",
  pro_generating: "Your file is being compiled securely...",
  pro_generating_btn: "Generating...",
  pro_next: "Next",
  pro_back: "Back",
  pro_close: "Close",
  pro_retry: "Try again",
  pro_error_title: "Could not generate",
  pro_error_text: "The file could not be generated. Please try again in a moment.",
  pro_result_title: "Your file is ready",
  pro_result_docnr: "File no.",
  pro_result_items: "Messages",
  pro_result_hash: "Integrity code (SHA-256)",
  pro_download_btn: "Download PDF file",
  pro_pdf_unavailable: "PDF unavailable",
  pro_upsell_title: "No solution yet?",
  pro_upsell_text: "Generate a professional handover file to give to a lawyer, mediator or HR. It shows that you tried to resolve it together.",
  pro_upsell_btn: "Create handover file"
};

// Partial overrides for other languages (using English as fallback for missing keys)
const createLang = (label: string, overrides: Partial<Record<TranslationKey, string>>) => {
  return { ...BASE_TRANSLATIONS, label, ...overrides };
};

export const UI_TRANSLATIONS: Record<string, any> = {
  nl: createLang("Nederlands", {
    tagline: "Ruzie op je werk of thuis?",
    tagline_highlight: "Los het vandaag nog op.",
    sub_tagline: "Jij spreekt je eigen taal, de ander ook. Onze AI mediator helpt jullie binnen 12 minuten naar een eerlijke oplossing.",
    start_btn: "Start nu – €3,99",
    micro_time: "Gemiddeld binnen 8–12 minuten inzicht",
    invited_btn: "Ik ben uitgenodigd",
    section_not_winning_title: "Niet winnen, maar oplossen",
    section_not_winning_text: "In een conflict is 'gelijk krijgen' vaak het einddoel, maar ten koste van wat? Rsolve richt zich op de toekomst. We helpen jullie om de emotie te parkeren en concrete afspraken te maken, zodat de relatie behouden blijft of netjes wordt afgerond.",
    what_is_title: "Wat is Rsolve?",
    what_is_p1: "Rsolve is een intelligent bemiddelingsplatform dat gebruik maakt van geavanceerde AI om conflicten neutraal en gestructureerd op te lossen. Zonder advocaten, zonder wachtlijsten.",
    what_is_list_1: "Neutrale gespreksleiding",
    what_is_list_2: "Concrete oplossingen",
    what_is_list_3: "Heldere afspraken",
    what_is_list_4: "Optionele Vaststellingsovereenkomst (VSO)",
    language_title: "Werkt in elke taal",
    language_text: "Taalbarrières escaleren conflicten vaak onnodig. Bij Rsolve typt iedereen in zijn eigen taal. Onze software vertaalt alles direct en foutloos, zodat jullie elkaar écht begrijpen. Ideaal voor expats en internationale teams.",
    when_title: "Wanneer werkt het?",
    when_text: "Rsolve is effectief in situaties waar communicatie is vastgelopen maar een oplossing noodzakelijk is:",
    why_title: "Waarom kiezen voor Rsolve?",
    why_1: "Geen dure advocaten",
    why_2: "Geen wachtlijsten",
    why_3: "Resultaat in minuten",
    why_4: "Kosten slechts €3,99",
    why_5: "Veilig & Vertrouwelijk",
    why_6: "Juridisch bruikbare afspraken",
    how_title: "Hoe werkt het?",
    how_step_1: "Start Dossier",
    how_step_2: "Nodig uit",
    how_step_3: "Begeleide Chat",
    how_step_4: "Vaststelling",
    faq_title: "Veelgestelde Vragen",
    faq_1_q: "Is het rechtsgeldig?",
    faq_1_a: "Ja, de afspraken kunnen worden vastgelegd in een Vaststellingsovereenkomst (VSO) conform Art. 7:900 BW. Dit document staat juridisch sterk.",
    faq_2_q: "Zijn mijn gegevens veilig?",
    faq_2_a: "Absoluut. Wij gebruiken geen gegevens voor trainingsdoeleinden en gesprekken zijn versleuteld.",
    faq_3_q: "Wat als de ander niet reageert?",
    faq_3_a: "Je betaalt eenmalig voor het dossier. Reageert de ander niet? Dan heb je in elk geval vastgelegd dat je hebt geprobeerd het samen op te lossen. Daarna is juridische hulp vaak de enige weg. Rsolve werkt samen met een netwerk van betrouwbare advocaten die we je kunnen voorstellen — via de pagina 'Juridische hulp' doe je vrijblijvend een aanvraag.",
    faq_4_q: "Voor wie is Rsolve?",
    faq_4_a: "Voor iedereen: werknemers, werkgevers, buren, ex-partners en zakelijke relaties.",
    faq_5_q: "Wat als de tegenpartij zich niet aan de vaststellingsovereenkomst houdt?",
    faq_5_a: "Een vaststellingsovereenkomst legt jullie afspraken juridisch bindend vast. Houdt de andere partij zich er toch niet aan, dan blijft er vaak geen andere weg over dan die naar de rechter en is het inschakelen van een advocaat meestal noodzakelijk. Het goede nieuws: in veel gevallen zal juist de partij die zich niet aan de afspraken houdt de zaak verliezen — een ondertekende VSO staat immers sterk als bewijs. Daarom is het vastleggen van je afspraken in een VSO altijd al een belangrijke stap in de goede richting.",
    footer_payoff: "Rsolve. Conflict oplossen zonder gedoe.",
    footer_expats: "Ook geschikt voor expats en internationale werknemers.",
    dossier: "Bewijs Dossier",
    items_collected: "items verzameld",
    no_evidence: "Nog geen bewijsmateriaal geüpload.",
    view_download: "Bekijken / Download",
    online: "is online",
    waiting: "Wachten op",
    placeholder: "Schrijf een bericht...",
    settings: "Taalinstellingen",
    dossier_status: "Dossier Status",
    invitation_sent: "Link verstuurd.",
    mediator: "Mediator",
    you: "Jij",
    system: "Systeem",
    payment_title: "Eénmalige Betaling",
    pay_btn: "Betaal €3,99",
    choosing_bank: "Kies je bank...",
    legal_vso: "Rechtsgeldige VSO door AI",
    disclaimer_title: "Belangrijke Informatie",
    disclaimer_body: "Rsolve geeft geen juridisch advies en vervangt geen advocaat.",
    disclaimer_agree: "Ik ga akkoord",
    nav_what_is: "Wat is mediation?",
    nav_start: "Start mediation",
    back_home: "Terug naar Home",
    payment_desc: "Betaling voor AI Mediation Dossier",
    secure_trans: "Veilige Transactie",
    pay_via_ideal: "Betaal via iDEAL",
    have_code: "Heb je een toegangscode?",
    enter_code: "Toegangscode Invoeren",
    validate_code: "OK",
    validating: "Valideren...",
    code_placeholder: "Bijv. RS-2024-XXXX",
    code_instruction: "Vul de code in die je hebt ontvangen.",
    payment_received: "Betaling Ontvangen!",
    lets_start: "Laten we starten.",
    label_your_name: "Jouw naam",
    label_subject: "Onderwerp conflict",
    label_counterparty: "Naam tegenpartij",
    btn_save_invite: "Opslaan & Uitnodigen",
    invite_header: "Nodig {name} uit",
    invite_desc: "Deel deze link via WhatsApp om te starten.",
    whatsapp_btn: "WhatsApp Uitnodiging",
    copy: "Kopieer",
    copied: "Gekopieerd",
    start_mediation_btn: "Start Mediation Gesprek",
    invited_header: "Je bent uitgenodigd",
    join_btn: "Deelnemen aan gesprek",
    join_free_notice: "Gratis deelname voor genodigden",
    leave_modal_title: "Mediation Verlaten?",
    leave_modal_desc: "Je kunt dit dossier niet meer openen.",
    leave_confirm: "Ja, verlaat sessie",
    leave_cancel: "Nee, ga door",
    leave_btn_label: "Stoppen",
    leave_legal_warning: "Let op: Het niet meewerken aan een oplossing kan in een eventuele latere rechtszaak in uw nadeel werken.",
    vso_modal_title: "Controleer Afspraken",
    vso_generating: "VSO wordt opgesteld...",
    vso_confirm: "Afspraken Bevestigen",
    finish_btn: "Afronden",
    leave_btn: "Verlaat",
    analysing: "Mediator analyseert...",
    vso_title: "Vaststellingsovereenkomst",
    legal_doc: "Rechtsgeldig Document",
    download_chat: "Chatverslag (.txt)",
    download_pdf: "Download PDF",
    settlement_agreement: "Vaststellingsovereenkomst",
    legal_accord: "Onderhands Gerechtelijk Akkoord • Rsolve AI",
    section_parties: "1. De Partijen",
    party_a: "Partij A",
    party_b: "Partij B",
    section_dispute: "2. Het Geschil",
    dispute_desc: "Partijen verklaren een geschil te hebben gehad over:",
    section_terms: "3. Overeengekomen Voorwaarden",
    no_terms: "Geen voorwaarden gespecificeerd.",
    section_final: "4. Finale Kwijting & Rechtskracht",
    final_text: "Partijen verlenen elkaar finale kwijting. Overeenkomst conform Art. 7:900 BW.",
    sign_party_a: "Handtekening Partij A",
    digital_sign: "Digitaal Ondertekend via Rsolve",
    ref: "Kenmerk:",
    date: "Datum:",
    sign_placeholder: "Typ volledige naam",
    sign_btn: "Zet Handtekening",
    sign_party_b: "Handtekening Partij B",
    waiting_sign: "Wacht op ondertekening...",
    congrats: "Gefeliciteerd!",
    signed_desc: "Jij hebt getekend. Wacht nu op de ander.",
    download_dossier: "Dossier Downloaden",
    delete_close: "Verwijder & Sluit",
    loading: "Laden...",
    error_generic: "Er ging iets mis.",
    dossier_not_found: "Dossier niet gevonden.",
    mediation_badge: "Mediation 2.0",
    when_work: "Werk",
    when_business: "Zakelijk",
    when_neighbors: "Buren",
    when_relations: "Relatie",
    plus_more: "+15...",
    placeholder_name: "Bijv. Mark",
    placeholder_subject: "Bijv. Terugbetaling lening",
    placeholder_invite: "Wie wil je uitnodigen?",
    secure_ssl: "Beveiligd door Rsolve SSL",
    typing_indicator: "is aan het typen...",
    mediator_thinking: "Mediator is aan het nadenken...",
    // Rsolve Pro (Fase 4)
    pro_header_btn: "Pro",
    pro_wizard_title: "Overdrachtsdossier genereren",
    pro_type_intro: "Kies welk document je wilt genereren.",
    pro_type_summary_label: "Samenvatting",
    pro_type_summary_desc: "Een beknopte, professionele samenvatting van het conflict en de huidige stand. Ideaal voor een eerste overdracht.",
    pro_type_full_label: "Volledig dossier",
    pro_type_full_desc: "De samenvatting plus de volledige conversatie als bronmateriaal.",
    pro_language_intro: "In welke taal moet het dossier worden opgesteld?",
    pro_language_label: "Dossiertaal",
    pro_language_hint: "De samenvatting wordt in deze taal geschreven. Originele verklaringen blijven bewaard.",
    pro_review_intro: "Dit wordt wél en niet in je dossier opgenomen.",
    pro_review_included_title: "Wordt opgenomen",
    pro_review_inc_conversation: "De gedeelde conversatie met de mediator",
    pro_review_inc_summary: "Een neutrale, door AI opgestelde samenvatting",
    pro_review_inc_own_notes: "Je eigen vertrouwelijke notities (indien aanwezig)",
    pro_review_inc_hash: "Een integriteitscode (SHA-256) en dossiernummer",
    pro_review_excluded_title: "Wordt niet opgenomen",
    pro_review_exc_other_notes: "De vertrouwelijke notities van de andere partij — nooit",
    pro_review_exc_judgment: "Geen juridisch oordeel of uitspraak",
    pro_consent_text: "Het dossier kan persoonsgegevens bevatten. Het wordt opgesteld voor overdracht aan een professional (advocaat, mediator, HR of verzekeraar) en is geen juridisch advies.",
    pro_consent_checkbox: "Ik begrijp dit en wil het dossier voor eigen gebruik genereren.",
    pro_generate_btn: "Genereren",
    pro_generating: "Je dossier wordt veilig samengesteld...",
    pro_generating_btn: "Bezig met genereren...",
    pro_next: "Volgende",
    pro_back: "Terug",
    pro_close: "Sluiten",
    pro_retry: "Opnieuw proberen",
    pro_error_title: "Genereren mislukt",
    pro_error_text: "Het dossier kon niet worden gegenereerd. Probeer het zo dadelijk opnieuw.",
    pro_result_title: "Je dossier is klaar",
    pro_result_docnr: "Dossiernr.",
    pro_result_items: "Berichten",
    pro_result_hash: "Integriteitscode (SHA-256)",
    pro_download_btn: "Download PDF-dossier",
    pro_pdf_unavailable: "PDF niet beschikbaar",
    pro_upsell_title: "Nog geen oplossing?",
    pro_upsell_text: "Genereer een professioneel overdrachtsdossier om aan een advocaat, mediator of HR te geven. Het laat zien dat je hebt geprobeerd om het samen op te lossen.",
    pro_upsell_btn: "Maak overdrachtsdossier"
  }),
  en: BASE_TRANSLATIONS,
  es: createLang("Español", {
    tagline: "Resolver conflictos,",
    tagline_highlight: "sin problemas.",
    sub_tagline: "Lleguen a una solución justa juntos con mediación IA.",
    start_btn: "Iniciar Mediación (€3,99)",
    nav_what_is: "¿Qué es la mediación?",
    nav_start: "Iniciar",
    payment_title: "Pago único",
    invite_header: "Invitar a {name}",
    vso_title: "Acuerdo de resolución",
    leave_modal_title: "¿Salir de la mediación?",
    vso_generating: "Redactando acuerdo...",
    analysing: "El mediador está analizando...",
    mediation_badge: "Mediación 2.0",
    when_work: "Trabajo",
    when_business: "Negocios",
    when_neighbors: "Vecinos",
    when_relations: "Relación",
    plus_more: "+15...",
    micro_time: "Información promedio en 8–12 minutos",
    section_not_winning_title: "Ganar no es resolver",
    section_not_winning_text: "En una pelea, nadie gana. La mediación se enfoca en encontrar un camino a seguir, preservando las relaciones y ahorrando tiempo.",
    what_is_title: "¿Qué es Rsolve?",
    what_is_p1: "Rsolve es una plataforma de mediación inteligente que utiliza IA avanzada para resolver conflictos de manera neutral y estructurada.",
    what_is_list_1: "Guía neutral",
    what_is_list_2: "Soluciones concretas",
    what_is_list_3: "Acuerdos claros",
    what_is_list_4: "Acuerdo de resolución opcional",
    language_title: "Funciona en todos los idiomas",
    language_text: "Las barreras del idioma a menudo escalan conflictos. En Rsolve, cada uno escribe en su propio idioma. Nuestro software traduce todo al instante.",
    when_title: "¿Cuándo funciona?",
    when_text: "Rsolve es efectivo en situaciones donde la comunicación se ha estancado pero es necesaria una solución:",
    why_title: "¿Por qué elegir Rsolve?",
    why_1: "Sin abogados costosos",
    why_2: "Sin listas de espera",
    why_3: "Resultados en minutos",
    why_4: "Cuesta solo €3,99",
    why_5: "Seguro y Confidencial",
    why_6: "Acuerdos legalmente válidos",
    how_title: "¿Cómo funciona?",
    how_step_1: "Iniciar Caso",
    how_step_2: "Invitar",
    how_step_3: "Chat Guiado",
    how_step_4: "Acuerdo",
    faq_title: "Preguntas Frecuentes",
    faq_1_q: "¿Es legalmente válido?",
    faq_1_a: "Sí, los acuerdos pueden formalizarse en un Acuerdo de Resolución (VSO).",
    faq_2_q: "¿Están seguros mis datos?",
    faq_2_a: "Absolutamente. Usamos encriptación y no compartimos datos con terceros.",
    faq_3_q: "¿Qué pasa si no responden?",
    faq_3_a: "Pagas una vez por el expediente. Si la otra parte no responde, al menos queda constancia de que intentaste resolverlo. A partir de ahí, la ayuda jurídica suele ser la única vía. Rsolve colabora con una red de abogados de confianza que podemos proponerte — puedes solicitarlo sin compromiso en la página 'Ayuda jurídica'.",
    faq_4_q: "¿Para quién es Rsolve?",
    faq_4_a: "Para todos: empleados, empleadores, vecinos y parejas.",
    faq_5_q: "¿Qué pasa si la otra parte no cumple el acuerdo de conciliación?",
    faq_5_a: "Un acuerdo de conciliación fija vuestros acuerdos de forma jurídicamente vinculante. Si la otra parte aun así no lo cumple, a menudo no queda otra vía que acudir a los tribunales, y normalmente es necesario contratar a un abogado. La buena noticia: en muchos casos es precisamente la parte que incumple el acuerdo la que acaba perdiendo, ya que un acuerdo firmado constituye una prueba sólida. Por eso, dejar vuestros acuerdos por escrito en un acuerdo de conciliación siempre es un paso importante en la dirección correcta.",
    footer_payoff: "Rsolve. Resolver conflictos sin líos.",
    footer_expats: "También apto para expatriados.",
    payment_received: "¡Pago Recibido!",
    lets_start: "Iniciemos el caso.",
    label_your_name: "Tu Nombre",
    label_subject: "Asunto del Conflicto",
    label_counterparty: "Nombre de la Contraparte",
    btn_save_invite: "Guardar e Invitar",
    invite_desc: "Comparte este enlace por WhatsApp para comenzar oficialmente.",
    whatsapp_btn: "Invitación por WhatsApp",
    copy: "Copiar",
    copied: "Copiado",
    start_mediation_btn: "Iniciar Chat de Mediación",
    join_btn: "Unirse a la Conversación",
    join_free_notice: "Participación gratuita para invitados",
    placeholder_name: "Ej. Marcos",
    placeholder_subject: "Ej. Devolución de dinero",
    placeholder_invite: "¿A quién quieres invitar?",
    payment_desc: "Pago único para expediente de mediación",
    secure_trans: "Transacción segura",
    pay_via_ideal: "Pagar vía iDEAL",
    choosing_bank: "Elige tu banco...",
    pay_btn: "Pagar €3,99",
    have_code: "¿Tienes un código de acceso?",
    enter_code: "Ingresar Código",
    validate_code: "Validar",
    validating: "Validando...",
    code_placeholder: "ej. RS-2024-XXXX",
    code_instruction: "Introduce el código proporcionado por tu empleador o aseguradora.",
    back_home: "Volver al inicio",
    secure_ssl: "Protegido por Rsolve SSL",
    typing_indicator: "está escribiendo...",
    mediator_thinking: "El mediador está pensando...",
    pro_header_btn: "Pro",
    pro_wizard_title: "Generar expediente de traspaso",
    pro_type_intro: "Elige qué documento quieres generar.",
    pro_type_summary_label: "Resumen",
    pro_type_summary_desc: "Un resumen conciso y profesional del conflicto y su estado actual. Ideal para un primer traspaso.",
    pro_type_full_label: "Expediente completo",
    pro_type_full_desc: "El resumen más la conversación completa como material de origen.",
    pro_language_intro: "¿En qué idioma debe redactarse el expediente?",
    pro_language_label: "Idioma del expediente",
    pro_language_hint: "El resumen se redacta en este idioma. Las declaraciones originales se conservan.",
    pro_review_intro: "Esto es lo que se incluirá y lo que no en tu expediente.",
    pro_review_included_title: "Se incluye",
    pro_review_inc_conversation: "La conversación compartida con el mediador",
    pro_review_inc_summary: "Un resumen neutral generado por IA",
    pro_review_inc_own_notes: "Tus propias notas confidenciales (si las hay)",
    pro_review_inc_hash: "Un código de integridad (SHA-256) y número de expediente",
    pro_review_excluded_title: "No se incluye",
    pro_review_exc_other_notes: "Las notas confidenciales de la otra parte — nunca",
    pro_review_exc_judgment: "Ningún juicio ni veredicto legal",
    pro_consent_text: "El expediente puede contener datos personales. Se genera para su traspaso a un profesional (abogado, mediador, RR. HH. o aseguradora) y no constituye asesoramiento legal.",
    pro_consent_checkbox: "Lo entiendo y quiero generar el expediente para mi propio uso.",
    pro_generate_btn: "Generar",
    pro_generating: "Tu expediente se está compilando de forma segura...",
    pro_generating_btn: "Generando...",
    pro_next: "Siguiente",
    pro_back: "Atrás",
    pro_close: "Cerrar",
    pro_retry: "Reintentar",
    pro_error_title: "No se pudo generar",
    pro_error_text: "No se pudo generar el expediente. Inténtalo de nuevo en un momento.",
    pro_result_title: "Tu expediente está listo",
    pro_result_docnr: "Nº exp.",
    pro_result_items: "Mensajes",
    pro_result_hash: "Código de integridad (SHA-256)",
    pro_download_btn: "Descargar expediente PDF",
    pro_pdf_unavailable: "PDF no disponible",
    pro_upsell_title: "¿Aún sin solución?",
    pro_upsell_text: "Genera un expediente de traspaso profesional para entregarlo a un abogado, mediador o RR. HH. Demuestra que intentaste resolverlo juntos.",
    pro_upsell_btn: "Crear expediente de traspaso"
  }),
  de: createLang("Deutsch", {
    tagline: "Konflikte lösen,",
    tagline_highlight: "ohne Ärger.",
    sub_tagline: "Finden Sie gemeinsam eine faire Lösung mit KI-Mediation.",
    start_btn: "Mediation starten (€3,99)",
    nav_what_is: "Was ist Mediation?",
    nav_start: "Starten",
    payment_title: "Einmalige Zahlung",
    invite_header: "{name} einladen",
    vso_title: "Feststellungsvereinbarung",
    leave_modal_title: "Mediation verlassen?",
    vso_generating: "Vereinbarung wird erstellt...",
    analysing: "Mediator analysiert...",
    mediation_badge: "Mediation 2.0",
    when_work: "Arbeit",
    when_business: "Geschäft",
    when_neighbors: "Nachbarn",
    when_relations: "Beziehung",
    plus_more: "+15...",
    micro_time: "Durchschnittliche Erkenntnis in 8–12 Minuten",
    section_not_winning_title: "Gewinnen ist keine Lösung",
    section_not_winning_text: "In einem Streit gewinnt niemand. Mediation konzentriert sich darauf, einen Weg nach vorne zu finden, Beziehungen zu bewahren und Zeit zu sparen.",
    what_is_title: "Was ist Rsolve?",
    what_is_p1: "Rsolve ist eine automatisierte Mediationsplattform, die KI nutzt, um Sie und die andere Partei zu einer Einigung zu führen.",
    what_is_list_1: "Neutrale Führung",
    what_is_list_2: "Konkrete Lösungen",
    what_is_list_3: "Klare Vereinbarungen",
    what_is_list_4: "Optionale Feststellungsvereinbarung",
    language_title: "Funktioniert in jeder Sprache",
    language_text: "Lassen Sie Sprachbarrieren keinen Konflikt eskalieren. Rsolve übersetzt alles sofort zwischen den Parteien.",
    when_title: "Am besten für...",
    when_text: "Arbeitskonflikte, Nachbarschaftsstreitigkeiten, Schuldenprobleme und Beziehungsmeinungsverschiedenheiten.",
    why_title: "Warum Rsolve wählen?",
    why_1: "Keine teuren Anwälte",
    why_2: "Keine langen Wartezeiten",
    why_3: "Ergebnisse in Minuten",
    why_4: "Kostet nur €3,99",
    why_5: "Sicher & Vertraulich",
    why_6: "Rechtlich nutzbare Vereinbarungen",
    how_title: "Wie es funktioniert",
    how_step_1: "Fall starten",
    how_step_2: "Partei einladen",
    how_step_3: "Geführter Chat",
    how_step_4: "Einigung",
    faq_title: "Häufig gestellte Fragen",
    faq_1_q: "Ist es rechtlich gültig?",
    faq_1_a: "Ja, die resultierende Vereinbarung kann rechtlich bindend sein.",
    faq_2_q: "Sind meine Daten sicher?",
    faq_2_a: "Wir verwenden Verschlüsselung und teilen Ihre privaten Daten nicht mit Dritten.",
    faq_3_q: "Was, wenn sie nicht antworten?",
    faq_3_a: "Sie zahlen einmalig für den Fall. Reagiert die andere Partei nicht, haben Sie zumindest festgehalten, dass Sie versucht haben, es zu lösen. Danach ist rechtliche Hilfe oft der einzige Weg. Rsolve arbeitet mit einem Netzwerk zuverlässiger Anwälte zusammen, die wir Ihnen vorschlagen können — über die Seite 'Rechtliche Hilfe' stellen Sie unverbindlich eine Anfrage.",
    faq_4_q: "Für wen ist Rsolve?",
    faq_4_a: "Jeden. Arbeitnehmer, Arbeitgeber, Nachbarn und Partner.",
    faq_5_q: "Was, wenn sich die Gegenpartei nicht an die Vergleichsvereinbarung hält?",
    faq_5_a: "Eine Vergleichsvereinbarung hält Ihre Absprachen rechtsverbindlich fest. Hält sich die andere Partei trotzdem nicht daran, bleibt oft nur der Weg zum Gericht, und die Einschaltung eines Anwalts ist meist notwendig. Die gute Nachricht: In vielen Fällen verliert gerade die Partei, die sich nicht an die Absprachen hält — eine unterschriebene Vereinbarung ist ein starkes Beweismittel. Deshalb ist das Festhalten Ihrer Absprachen in einer Vergleichsvereinbarung immer schon ein wichtiger Schritt in die richtige Richtung.",
    footer_payoff: "Rsolve. Konflikte lösen ohne Ärger.",
    footer_expats: "Geeignet für Expats und internationale Arbeitnehmer.",
    payment_received: "Zahlung erhalten!",
    lets_start: "Lassen Sie uns den Fall beginnen.",
    label_your_name: "Ihr Name",
    label_subject: "Konfliktthema",
    label_counterparty: "Name der Gegenpartei",
    btn_save_invite: "Speichern & Einladen",
    invite_desc: "Teilen Sie diesen Link per WhatsApp, um offiziell zu beginnen.",
    whatsapp_btn: "WhatsApp Einladung",
    copy: "Kopieren",
    copied: "Kopiert",
    start_mediation_btn: "Mediations-Chat starten",
    invited_header: "Sie sind eingeladen",
    join_btn: "Gespräch beitreten",
    join_free_notice: "Kostenlose Teilnahme für Eingeladene",
    placeholder_name: "z.B. Markus",
    placeholder_subject: "z.B. Rückzahlung Darlehen",
    placeholder_invite: "Wen möchten Sie einladen?",
    payment_desc: "Zahlung für KI-Mediationsfall",
    secure_trans: "Sichere Transaktion",
    pay_via_ideal: "Zahlen via iDEAL/Bank",
    choosing_bank: "Wählen Sie Ihre Bank...",
    pay_btn: "Zahlen €3,99",
    have_code: "Haben Sie einen Zugangscode?",
    enter_code: "Zugangscode eingeben",
    validate_code: "Prüfen",
    validating: "Wird überprüft...",
    code_placeholder: "z.B. RS-2024-XXXX",
    code_instruction: "Geben Sie den Code Ihres Arbeitgebers oder Versicherers ein.",
    back_home: "Zurück zur Startseite",
    secure_ssl: "Gesichert durch Rsolve SSL",
    typing_indicator: "schreibt...",
    mediator_thinking: "Mediator denkt nach...",
    pro_header_btn: "Pro",
    pro_wizard_title: "Übergabedossier erstellen",
    pro_type_intro: "Wählen Sie, welches Dokument Sie erstellen möchten.",
    pro_type_summary_label: "Zusammenfassung",
    pro_type_summary_desc: "Eine prägnante, professionelle Zusammenfassung des Konflikts und des aktuellen Stands. Ideal für eine erste Übergabe.",
    pro_type_full_label: "Vollständiges Dossier",
    pro_type_full_desc: "Die Zusammenfassung plus das vollständige Gespräch als Quellenmaterial.",
    pro_language_intro: "In welcher Sprache soll das Dossier verfasst werden?",
    pro_language_label: "Dossiersprache",
    pro_language_hint: "Die Zusammenfassung wird in dieser Sprache verfasst. Originalaussagen bleiben erhalten.",
    pro_review_intro: "Das wird in Ihr Dossier aufgenommen und das nicht.",
    pro_review_included_title: "Enthalten",
    pro_review_inc_conversation: "Das gemeinsame Gespräch mit dem Mediator",
    pro_review_inc_summary: "Eine neutrale, KI-erstellte Zusammenfassung",
    pro_review_inc_own_notes: "Ihre eigenen vertraulichen Notizen (falls vorhanden)",
    pro_review_inc_hash: "Ein Integritätscode (SHA-256) und eine Dossiernummer",
    pro_review_excluded_title: "Nicht enthalten",
    pro_review_exc_other_notes: "Die vertraulichen Notizen der anderen Partei — niemals",
    pro_review_exc_judgment: "Kein rechtliches Urteil oder Verdikt",
    pro_consent_text: "Das Dossier kann personenbezogene Daten enthalten. Es wird zur Übergabe an einen Fachmann (Anwalt, Mediator, Personalabteilung oder Versicherer) erstellt und ist keine Rechtsberatung.",
    pro_consent_checkbox: "Ich verstehe dies und möchte das Dossier zur eigenen Verwendung erstellen.",
    pro_generate_btn: "Erstellen",
    pro_generating: "Ihr Dossier wird sicher zusammengestellt...",
    pro_generating_btn: "Wird erstellt...",
    pro_next: "Weiter",
    pro_back: "Zurück",
    pro_close: "Schließen",
    pro_retry: "Erneut versuchen",
    pro_error_title: "Erstellung fehlgeschlagen",
    pro_error_text: "Das Dossier konnte nicht erstellt werden. Bitte versuchen Sie es gleich erneut.",
    pro_result_title: "Ihr Dossier ist fertig",
    pro_result_docnr: "Dossier-Nr.",
    pro_result_items: "Nachrichten",
    pro_result_hash: "Integritätscode (SHA-256)",
    pro_download_btn: "PDF-Dossier herunterladen",
    pro_pdf_unavailable: "PDF nicht verfügbar",
    pro_upsell_title: "Noch keine Lösung?",
    pro_upsell_text: "Erstellen Sie ein professionelles Übergabedossier für einen Anwalt, Mediator oder die Personalabteilung. Es zeigt, dass Sie versucht haben, es gemeinsam zu lösen.",
    pro_upsell_btn: "Übergabedossier erstellen"
  }),
  fr: createLang("Français", {
    tagline: "Résoudre les conflits,",
    tagline_highlight: "sans tracas.",
    sub_tagline: "Trouvez une solution équitable ensemble avec l'aide de l'IA.",
    start_btn: "Démarrer Médiation (€3,99)",
    nav_what_is: "Qu'est-ce que la médiation?",
    nav_start: "Démarrer",
    payment_title: "Paiement unique",
    invite_header: "Inviter {name}",
    vso_title: "Accord de règlement",
    leave_modal_title: "Quitter la médiation?",
    vso_generating: "Rédaction de l'accord...",
    analysing: "Le médiateur analyse...",
    mediation_badge: "Médiation 2.0",
    when_work: "Travail",
    when_business: "Affaires",
    when_neighbors: "Voisins",
    when_relations: "Relation",
    plus_more: "+15...",
    micro_time: "Aperçu moyen en 8–12 minutes",
    section_not_winning_title: "Gagner n'est pas résoudre",
    section_not_winning_text: "Dans une dispute, personne ne gagne. La médiation se concentre sur la recherche d'une solution, la préservation des relations et le gain de temps.",
    what_is_title: "Qu'est-ce que Rsolve ?",
    what_is_p1: "Rsolve est une plateforme de médiation automatisée qui utilise l'IA pour vous guider, vous et l'autre partie, vers un accord.",
    what_is_list_1: "Guidance neutre",
    what_is_list_2: "Solutions concrètes",
    what_is_list_3: "Accords clairs",
    what_is_list_4: "Accord de règlement optionnel",
    language_title: "Fonctionne dans toutes les langues",
    language_text: "Ne laissez pas les barrières linguistiques aggraver un conflit. Rsolve traduit tout instantanément entre les parties.",
    when_title: "Idéal pour...",
    when_text: "Conflits du travail, conflits de voisinage, problèmes de dettes et désaccords relationnels.",
    why_title: "Pourquoi choisir Rsolve ?",
    why_1: "Pas d'avocats coûteux",
    why_2: "Pas de longs délais d'attente",
    why_3: "Résultats en quelques minutes",
    why_4: "Ne coûte que 3,99 €",
    why_5: "Sûr et confidentiel",
    why_6: "Accords juridiquement utilisables",
    how_title: "Comment ça marche",
    how_step_1: "Démarrer le cas",
    how_step_2: "Inviter la partie",
    how_step_3: "Chat guidé",
    how_step_4: "Accord",
    faq_title: "Questions fréquentes",
    faq_1_q: "Est-ce juridiquement valable ?",
    faq_1_a: "Oui, l'accord résultant peut être juridiquement contraignant.",
    faq_2_q: "Mes données sont-elles en sécurité ?",
    faq_2_a: "Nous utilisons le cryptage et ne partageons pas vos données privées avec des tiers.",
    faq_3_q: "Et s'ils ne répondent pas ?",
    faq_3_a: "Vous ne payez qu'une seule fois pour le dossier. Si l'autre partie ne répond pas, vous avez au moins la preuve que vous avez essayé de résoudre le problème. Ensuite, l'aide juridique est souvent la seule voie. Rsolve collabore avec un réseau d'avocats de confiance que nous pouvons vous proposer — vous pouvez faire une demande sans engagement via la page 'Aide juridique'.",
    faq_4_q: "Pour qui est Rsolve ?",
    faq_4_a: "Tout le monde. Employés, employeurs, voisins et partenaires.",
    faq_5_q: "Que se passe-t-il si l'autre partie ne respecte pas l'accord transactionnel ?",
    faq_5_a: "Un accord transactionnel fixe vos arrangements de manière juridiquement contraignante. Si l'autre partie ne le respecte pas malgré tout, il ne reste souvent d'autre voie que celle du tribunal, et le recours à un avocat est généralement nécessaire. La bonne nouvelle : dans de nombreux cas, c'est justement la partie qui ne respecte pas l'accord qui finira par perdre — un accord signé constitue une preuve solide. C'est pourquoi consigner vos arrangements dans un accord transactionnel est toujours un pas important dans la bonne direction.",
    footer_payoff: "Rsolve. Résoudre les conflits sans tracas.",
    footer_expats: "Convient aux expatriés et aux travailleurs internationaux.",
    payment_received: "Paiement reçu !",
    lets_start: "Commençons le dossier.",
    label_your_name: "Votre nom",
    label_subject: "Sujet du conflit",
    label_counterparty: "Nom de la partie adverse",
    btn_save_invite: "Enregistrer et inviter",
    invite_desc: "Partagez ce lien via WhatsApp pour commencer officiellement.",
    whatsapp_btn: "Invitation WhatsApp",
    copy: "Copier",
    copied: "Copié",
    start_mediation_btn: "Démarrer le chat de médiation",
    invited_header: "Vous êtes invité",
    join_btn: "Rejoindre la conversation",
    join_free_notice: "Participation gratuite pour les invités",
    placeholder_name: "ex. Marc",
    placeholder_subject: "ex. Remboursement de prêt",
    placeholder_invite: "Qui inviter ?",
    payment_desc: "Paiement pour dossier de médiation IA",
    secure_trans: "Transaction sécurisée",
    pay_via_ideal: "Payer via Banque",
    choosing_bank: "Choisissez votre banque...",
    pay_btn: "Payer 3,99 €",
    have_code: "Avez-vous un code d'accès ?",
    enter_code: "Entrer le code",
    validate_code: "Valider",
    validating: "Validation...",
    code_placeholder: "ex. RS-2024-XXXX",
    code_instruction: "Entrez le code fourni par votre employeur ou assureur.",
    back_home: "Retour à l'accueil",
    secure_ssl: "Sécurisé par Rsolve SSL",
    typing_indicator: "est en train d'écrire...",
    mediator_thinking: "Le médiateur réfléchit...",
    pro_header_btn: "Pro",
    pro_wizard_title: "Générer le dossier de transmission",
    pro_type_intro: "Choisissez le document que vous souhaitez générer.",
    pro_type_summary_label: "Résumé",
    pro_type_summary_desc: "Un résumé concis et professionnel du conflit et de son état actuel. Idéal pour une première transmission.",
    pro_type_full_label: "Dossier complet",
    pro_type_full_desc: "Le résumé plus la conversation complète comme matériel source.",
    pro_language_intro: "Dans quelle langue le dossier doit-il être rédigé ?",
    pro_language_label: "Langue du dossier",
    pro_language_hint: "Le résumé est rédigé dans cette langue. Les déclarations originales sont conservées.",
    pro_review_intro: "Voici ce qui sera inclus ou non dans votre dossier.",
    pro_review_included_title: "Inclus",
    pro_review_inc_conversation: "La conversation partagée avec le médiateur",
    pro_review_inc_summary: "Un résumé neutre généré par l'IA",
    pro_review_inc_own_notes: "Vos propres notes confidentielles (le cas échéant)",
    pro_review_inc_hash: "Un code d'intégrité (SHA-256) et un numéro de dossier",
    pro_review_excluded_title: "Non inclus",
    pro_review_exc_other_notes: "Les notes confidentielles de l'autre partie — jamais",
    pro_review_exc_judgment: "Aucun jugement ni verdict juridique",
    pro_consent_text: "Le dossier peut contenir des données personnelles. Il est généré pour être transmis à un professionnel (avocat, médiateur, RH ou assureur) et ne constitue pas un conseil juridique.",
    pro_consent_checkbox: "Je comprends ceci et je souhaite générer le dossier pour mon usage personnel.",
    pro_generate_btn: "Générer",
    pro_generating: "Votre dossier est compilé en toute sécurité...",
    pro_generating_btn: "Génération...",
    pro_next: "Suivant",
    pro_back: "Retour",
    pro_close: "Fermer",
    pro_retry: "Réessayer",
    pro_error_title: "Échec de la génération",
    pro_error_text: "Le dossier n'a pas pu être généré. Veuillez réessayer dans un instant.",
    pro_result_title: "Votre dossier est prêt",
    pro_result_docnr: "N° dossier",
    pro_result_items: "Messages",
    pro_result_hash: "Code d'intégrité (SHA-256)",
    pro_download_btn: "Télécharger le dossier PDF",
    pro_pdf_unavailable: "PDF indisponible",
    pro_upsell_title: "Toujours pas de solution ?",
    pro_upsell_text: "Générez un dossier de transmission professionnel à remettre à un avocat, un médiateur ou les RH. Il montre que vous avez tenté de résoudre le conflit ensemble.",
    pro_upsell_btn: "Créer le dossier de transmission"
  }),
  tr: createLang("Türkçe", {
    tagline: "Anlaşmazlığı çözün,",
    tagline_highlight: "zahmetsizce.",
    sub_tagline: "AI arabuluculuğu yardımıyla birlikte adil bir çözüme ulaşın.",
    start_btn: "Arabuluculuğu Başlat (€3,99)",
    invited_btn: "Davet edildim",
    nav_what_is: "Arabuluculuk nedir?",
    nav_start: "Başlat",
    payment_title: "Tek Seferlik Ödeme",
    invite_header: "{name} davet et",
    vso_title: "Uzlaşma Anlaşması",
    leave_modal_title: "Ayrılmak mı?",
    vso_generating: "Anlaşma hazırlanıyor...",
    analysing: "Arabulucu analiz ediyor...",
    dossier: "Dosya",
    mediator: "Arabulucu",
    you: "Sen",
    leave_confirm: "Evet, ayrıl",
    leave_cancel: "Hayır, devam et",
    mediation_badge: "Arabuluculuk 2.0",
    when_work: "İş",
    when_business: "İşletme",
    when_neighbors: "Komşular",
    when_relations: "İlişki",
    plus_more: "+15...",
    micro_time: "8–12 dakika içinde ortalama içgörü",
    section_not_winning_title: "Kazanmak çözüm değildir",
    section_not_winning_text: "Bir kavgada kimse kazanmaz. Arabuluculuk, ilişkileri koruyarak ve zaman kazandırarak ileriye dönük bir yol bulmaya odaklanır.",
    what_is_title: "Rsolve nedir?",
    what_is_p1: "Rsolve, sizi ve diğer tarafı bir anlaşmaya yönlendirmek için yapay zeka kullanan otomatik bir arabuluculuk platformudur.",
    what_is_list_1: "Tarafsız rehberlik",
    what_is_list_2: "Somut çözümler",
    what_is_list_3: "Net anlaşmalar",
    what_is_list_4: "İsteğe bağlı Uzlaşma Anlaşması",
    language_title: "Her dilde çalışır",
    language_text: "Dil engellerinin bir çatışmayı tırmandırmasına izin vermeyin. Rsolve, taraflar arasında her şeyi anında çevirir.",
    when_title: "En iyisi...",
    when_text: "İş anlaşmazlıkları, komşu çatışmaları, borç sorunları ve ilişki anlaşmazlıkları.",
    why_title: "Neden Rsolve'u seçmelisiniz?",
    why_1: "Pahalı avukatlar yok",
    why_2: "Uzun bekleme süreleri yok",
    why_3: "Dakikalar içinde sonuç",
    why_4: "Sadece 3,99 €",
    why_5: "Güvenli ve Gizli",
    why_6: "Yasal olarak kullanılabilir anlaşmalar",
    how_title: "Nasıl çalışır",
    how_step_1: "Davayı Başlat",
    how_step_2: "Tarafı Davet Et",
    how_step_3: "Yönlendirilmiş Sohbet",
    how_step_4: "Anlaşma",
    faq_title: "Sıkça Sorulan Sorular",
    faq_1_q: "Yasal olarak geçerli mi?",
    faq_1_a: "Evet, ortaya çıkan anlaşma yasal olarak bağlayıcı olabilir.",
    faq_2_q: "Verilerim güvende mi?",
    faq_2_a: "Şifreleme kullanıyoruz ve özel verilerinizi üçüncü taraflarla paylaşmıyoruz.",
    faq_3_q: "Ya cevap vermezlerse?",
    faq_3_a: "Dosya için bir kez ödeme yaparsınız. Karşı taraf yanıt vermezse, en azından sorunu çözmeye çalıştığınız kayıt altında olur. Bundan sonra hukuki yardım genellikle tek yoldur. Rsolve, size önerebileceğimiz güvenilir avukatlardan oluşan bir ağ ile çalışır — 'Hukuki yardım' sayfasından yükümlülük olmadan talep oluşturabilirsiniz.",
    faq_4_q: "Rsolve kimin için?",
    faq_4_a: "Herkes. Çalışanlar, işverenler, komşular ve ortaklar.",
    faq_5_q: "Karşı taraf sulh sözleşmesine uymazsa ne olur?",
    faq_5_a: "Sulh sözleşmesi, üzerinde anlaştığınız hususları hukuken bağlayıcı şekilde kayıt altına alır. Karşı taraf yine de uymazsa, çoğu zaman mahkemeye başvurmaktan başka yol kalmaz ve genellikle bir avukata başvurmak gerekir. İyi haber: birçok durumda anlaşmaya uymayan taraf davayı kaybeder — imzalı bir sözleşme güçlü bir delildir. Bu yüzden anlaştığınız hususları bir sulh sözleşmesinde kayıt altına almak her zaman doğru yönde atılmış önemli bir adımdır.",
    footer_payoff: "Rsolve. Çatışmayı zahmetsizce çözme.",
    footer_expats: "Gurbetçiler ve uluslararası çalışanlar için uygundur.",
    payment_received: "Ödeme Alındı!",
    lets_start: "Davayı başlatalım.",
    label_your_name: "Adınız",
    label_subject: "Anlaşmazlık Konusu",
    label_counterparty: "Karşı Tarafın Adı",
    btn_save_invite: "Kaydet ve Davet Et",
    invite_desc: "Resmi olarak başlamak için bu bağlantıyı WhatsApp üzerinden paylaşın.",
    whatsapp_btn: "WhatsApp Davetiyesi",
    copy: "Kopyala",
    copied: "Kopyalandı",
    start_mediation_btn: "Arabuluculuk Sohbetini Başlat",
    invited_header: "Davet edildiniz",
    join_btn: "Sohbete Katıl",
    join_free_notice: "Davetliler için ücretsiz katılım",
    placeholder_name: "örn. Mehmet",
    placeholder_subject: "örn. Borç ödeme",
    placeholder_invite: "Kimi davet etmek istersiniz?",
    payment_desc: "Yapay Zeka Arabuluculuk Dosyası Ödemesi",
    secure_trans: "Güvenli İşlem",
    pay_via_ideal: "Banka ile Öde",
    choosing_bank: "Bankanızı seçin...",
    pay_btn: "Öde €3,99",
    have_code: "Erişim kodunuz var mı?",
    enter_code: "Kodu Girin",
    validate_code: "Doğrula",
    validating: "Doğrulanıyor...",
    code_placeholder: "örn. RS-2024-XXXX",
    code_instruction: "İşvereniniz veya sigortacınız tarafından verilen kodu girin.",
    back_home: "Ana Sayfaya Dön",
    secure_ssl: "Rsolve SSL ile Güvenli",
    typing_indicator: "yazıyor...",
    mediator_thinking: "Arabulucu düşünüyor...",
    pro_header_btn: "Pro",
    pro_wizard_title: "Devir dosyası oluştur",
    pro_type_intro: "Hangi belgeyi oluşturmak istediğinizi seçin.",
    pro_type_summary_label: "Özet",
    pro_type_summary_desc: "Anlaşmazlığın ve mevcut durumun kısa, profesyonel bir özeti. İlk devir için idealdir.",
    pro_type_full_label: "Tam dosya",
    pro_type_full_desc: "Özet ve kaynak materyal olarak tüm görüşme.",
    pro_language_intro: "Dosya hangi dilde yazılmalı?",
    pro_language_label: "Dosya dili",
    pro_language_hint: "Özet bu dilde yazılır. Orijinal beyanlar korunur.",
    pro_review_intro: "Dosyanıza nelerin dahil edilip edilmeyeceği aşağıdadır.",
    pro_review_included_title: "Dahil edilir",
    pro_review_inc_conversation: "Arabulucuyla paylaşılan görüşme",
    pro_review_inc_summary: "Yapay zeka tarafından oluşturulan tarafsız bir özet",
    pro_review_inc_own_notes: "Kendi gizli notlarınız (varsa)",
    pro_review_inc_hash: "Bir bütünlük kodu (SHA-256) ve dosya numarası",
    pro_review_excluded_title: "Dahil edilmez",
    pro_review_exc_other_notes: "Diğer tarafın gizli notları — asla",
    pro_review_exc_judgment: "Hukuki bir hüküm veya karar yok",
    pro_consent_text: "Dosya kişisel veriler içerebilir. Bir uzmana (avukat, arabulucu, İK veya sigortacı) devredilmek üzere oluşturulur ve hukuki tavsiye değildir.",
    pro_consent_checkbox: "Bunu anlıyorum ve dosyayı kendi kullanımım için oluşturmak istiyorum.",
    pro_generate_btn: "Oluştur",
    pro_generating: "Dosyanız güvenli bir şekilde derleniyor...",
    pro_generating_btn: "Oluşturuluyor...",
    pro_next: "İleri",
    pro_back: "Geri",
    pro_close: "Kapat",
    pro_retry: "Tekrar dene",
    pro_error_title: "Oluşturulamadı",
    pro_error_text: "Dosya oluşturulamadı. Lütfen birazdan tekrar deneyin.",
    pro_result_title: "Dosyanız hazır",
    pro_result_docnr: "Dosya no.",
    pro_result_items: "Mesajlar",
    pro_result_hash: "Bütünlük kodu (SHA-256)",
    pro_download_btn: "PDF dosyasını indir",
    pro_pdf_unavailable: "PDF kullanılamıyor",
    pro_upsell_title: "Hâlâ çözüm yok mu?",
    pro_upsell_text: "Bir avukata, arabulucuya veya İK'ya vermek için profesyonel bir devir dosyası oluşturun. Sorunu birlikte çözmeye çalıştığınızı gösterir.",
    pro_upsell_btn: "Devir dosyası oluştur"
  }),
  ar: createLang("العربية", {
    tagline: "حل النزاع،",
    tagline_highlight: "دون عناء.",
    sub_tagline: "توصلوا إلى حل عادل معًا بمساعدة الذكاء الاصطناعي.",
    start_btn: "بدء الوساطة (€3.99)",
    micro_time: "رؤية متوسطة في 8-12 دقيقة",
    section_not_winning_title: "الفوز ليس حلاً",
    section_not_winning_text: "في القتال، لا أحد يفوز. تركز الوساطة على إيجاد طريق للمضي قدمًا، والحفاظ على العلاقات، وتوفير الوقت.",
    what_is_title: "ما هو Rsolve؟",
    what_is_p1: "Rsolve هي منصة وساطة آلية تستخدم الذكاء الاصطناعي لإرشادك والطرف الآخر إلى اتفاق.",
    what_is_list_1: "توجيه محايد",
    what_is_list_2: "حلول ملموسة",
    what_is_list_3: "اتفاقيات واضحة",
    what_is_list_4: "اتفاقية تسوية اختيارية",
    language_title: "يعمل بكل لغة",
    language_text: "لا تدع حواجز اللغة تصعد النزاع. يترجم Rsolve كل شيء فورًا بين الأطراف.",
    when_title: "الأفضل لـ...",
    when_text: "النزاعات العمالية، صراعات الجيران، قضايا الديون، وخلافات العلاقات.",
    why_title: "لماذا تختار Rsolve؟",
    why_1: "لا محامين باهظين",
    why_2: "لا أوقات انتظار طويلة",
    why_3: "نتائج في دقائق",
    why_4: "التكلفة فقط €3.99",
    why_5: "آمن وسري",
    why_6: "اتفاقيات صالحة قانونًا",
    how_title: "كيف يعمل",
    how_step_1: "بدء القضية",
    how_step_2: "دعوة الطرف",
    how_step_3: "دردشة موجهة",
    how_step_4: "اتفاق",
    faq_title: "أسئلة مكررة",
    footer_payoff: "Rsolve. حل النزاع دون عناء.",
    footer_expats: "مناسب للمغتربين والعاملين الدوليين.",
    nav_what_is: "ما هي الوساطة؟",
    nav_start: "يبدأ",
    payment_title: "دفع لمرة واحدة",
    invite_header: "دعوة {name}",
    vso_title: "اتفاقية تسوية",
    leave_modal_title: "مغادرة الوساطة؟",
    vso_generating: "جاري صياغة الاتفاقية...",
    analysing: "الوسيط يحلل...",
    mediator: "الوسيط",
    you: "أنت",
    dossier: "ملف",
    join_btn: "انضم للمحادثة",
    typing_indicator: "يكتب...",
    mediator_thinking: "الوسيط يفكر...",
    pro_header_btn: "Pro",
    pro_wizard_title: "إنشاء ملف التسليم",
    pro_type_intro: "اختر المستند الذي تريد إنشاءه.",
    pro_type_summary_label: "ملخّص",
    pro_type_summary_desc: "ملخّص موجز ومهني للنزاع وحالته الحالية. مثالي للتسليم الأول.",
    pro_type_full_label: "ملف كامل",
    pro_type_full_desc: "الملخّص بالإضافة إلى المحادثة الكاملة كمادة مصدرية.",
    pro_language_intro: "بأي لغة ينبغي كتابة الملف؟",
    pro_language_label: "لغة الملف",
    pro_language_hint: "يُكتب الملخّص بهذه اللغة. ويُحتفظ بالأقوال الأصلية.",
    pro_review_intro: "هذا ما سيُدرَج وما لن يُدرَج في ملفك.",
    pro_review_included_title: "مُدرَج",
    pro_review_inc_conversation: "المحادثة المشتركة مع الوسيط",
    pro_review_inc_summary: "ملخّص محايد أنشأه الذكاء الاصطناعي",
    pro_review_inc_own_notes: "ملاحظاتك السرية الخاصة (إن وُجدت)",
    pro_review_inc_hash: "رمز سلامة (SHA-256) ورقم الملف",
    pro_review_excluded_title: "غير مُدرَج",
    pro_review_exc_other_notes: "الملاحظات السرية للطرف الآخر — أبداً",
    pro_review_exc_judgment: "لا حكم أو قرار قانوني",
    pro_consent_text: "قد يحتوي الملف على بيانات شخصية. يُنشأ لتسليمه إلى مختص (محامٍ أو وسيط أو الموارد البشرية أو شركة تأمين) وهو ليس استشارة قانونية.",
    pro_consent_checkbox: "أفهم ذلك وأرغب في إنشاء الملف لاستخدامي الشخصي.",
    pro_generate_btn: "إنشاء",
    pro_generating: "يجري تجميع ملفك بأمان...",
    pro_generating_btn: "جارٍ الإنشاء...",
    pro_next: "التالي",
    pro_back: "رجوع",
    pro_close: "إغلاق",
    pro_retry: "إعادة المحاولة",
    pro_error_title: "تعذّر الإنشاء",
    pro_error_text: "تعذّر إنشاء الملف. يرجى المحاولة مرة أخرى بعد قليل.",
    pro_result_title: "ملفك جاهز",
    pro_result_docnr: "رقم الملف",
    pro_result_items: "الرسائل",
    pro_result_hash: "رمز السلامة (SHA-256)",
    pro_download_btn: "تنزيل ملف PDF",
    pro_pdf_unavailable: "PDF غير متاح",
    pro_upsell_title: "لا يوجد حل بعد؟",
    pro_upsell_text: "أنشئ ملف تسليم مهنياً لتقديمه إلى محامٍ أو وسيط أو الموارد البشرية. يُظهر أنك حاولت حلّ الأمر معاً.",
    pro_upsell_btn: "إنشاء ملف التسليم"
  }),
  pl: createLang("Polski", {
    tagline: "Rozwiąż konflikt,",
    tagline_highlight: "bez problemów.",
    sub_tagline: "Znajdźcie sprawiedliwe rozwiązanie razem z pomocą AI.",
    start_btn: "Rozpocznij mediację (€3,99)",
    micro_time: "Średni czas wglądu 8–12 minut",
    section_not_winning_title: "Wygrana to nie rozwiązanie",
    section_not_winning_text: "W walce nikt nie wygrywa. Mediacja skupia się na znalezieniu drogi naprzód, zachowaniu relacji i oszczędności czasu.",
    what_is_title: "Czym jest Rsolve?",
    what_is_p1: "Rsolve to zautomatyzowana platforma mediacyjna wykorzystująca AI, by poprowadzić ciebie i drugą stronę do porozumienia.",
    what_is_list_1: "Neutralne prowadzenie",
    what_is_list_2: "Konkrete rozwiązania",
    what_is_list_3: "Jasne ustalenia",
    what_is_list_4: "Opcjonalna ugoda (VSO)",
    language_title: "Działa w każdym języku",
    language_text: "Nie pozwól, by bariery językowe eskalowały konflikt. Rsolve tłumaczy wszystko natychmiastowo.",
    when_title: "Najlepsze dla...",
    when_text: "Sporów pracowniczych, konfliktów sąsiedzkich, długów i nieporozumień w związkach.",
    why_title: "Dlaczego Rsolve?",
    why_1: "Bez drogich prawników",
    why_2: "Bez długiego czekania",
    why_3: "Wyniki w minuty",
    why_4: "Koszt tylko €3,99",
    why_5: "Bezpieczne i poufne",
    why_6: "Prawnie użyteczne ugody",
    how_title: "Jak to działa",
    how_step_1: "Rozpocznij sprawę",
    how_step_2: "Zaproś stronę",
    how_step_3: "Czat z przewodnikiem",
    how_step_4: "Porozumienie",
    faq_title: "Częste pytania",
    footer_payoff: "Rsolve. Rozwiązywanie konfliktów bez kłopotów.",
    footer_expats: "Odpowiednie dla emigrantów i pracowników międzynarodowych.",
    nav_what_is: "Czym jest mediacja?",
    nav_start: "Start",
    payment_title: "Jednorazowa płatność",
    invite_header: "Zaproś {name}",
    vso_title: "Ugoda",
    leave_modal_title: "Opuścić mediację?",
    vso_generating: "Tworzenie ugody...",
    analysing: "Mediator analizuje...",
    typing_indicator: "pisze...",
    mediator_thinking: "Mediator myśli...",
    pro_header_btn: "Pro",
    pro_wizard_title: "Wygeneruj akta przekazania",
    pro_type_intro: "Wybierz dokument, który chcesz wygenerować.",
    pro_type_summary_label: "Podsumowanie",
    pro_type_summary_desc: "Zwięzłe, profesjonalne podsumowanie sporu i jego bieżącego stanu. Idealne do pierwszego przekazania.",
    pro_type_full_label: "Pełne akta",
    pro_type_full_desc: "Podsumowanie oraz pełna rozmowa jako materiał źródłowy.",
    pro_language_intro: "W jakim języku mają zostać sporządzone akta?",
    pro_language_label: "Język akt",
    pro_language_hint: "Podsumowanie jest sporządzane w tym języku. Oryginalne oświadczenia są zachowywane.",
    pro_review_intro: "Oto co zostanie, a co nie zostanie ujęte w Twoich aktach.",
    pro_review_included_title: "Ujęte",
    pro_review_inc_conversation: "Wspólna rozmowa z mediatorem",
    pro_review_inc_summary: "Neutralne podsumowanie wygenerowane przez SI",
    pro_review_inc_own_notes: "Twoje własne poufne notatki (jeśli istnieją)",
    pro_review_inc_hash: "Kod integralności (SHA-256) i numer akt",
    pro_review_excluded_title: "Nieujęte",
    pro_review_exc_other_notes: "Poufne notatki drugiej strony — nigdy",
    pro_review_exc_judgment: "Żadnego osądu ani wyroku prawnego",
    pro_consent_text: "Akta mogą zawierać dane osobowe. Są generowane w celu przekazania specjaliście (prawnikowi, mediatorowi, HR lub ubezpieczycielowi) i nie stanowią porady prawnej.",
    pro_consent_checkbox: "Rozumiem to i chcę wygenerować akta na własny użytek.",
    pro_generate_btn: "Generuj",
    pro_generating: "Twoje akta są bezpiecznie kompletowane...",
    pro_generating_btn: "Generowanie...",
    pro_next: "Dalej",
    pro_back: "Wstecz",
    pro_close: "Zamknij",
    pro_retry: "Spróbuj ponownie",
    pro_error_title: "Nie udało się wygenerować",
    pro_error_text: "Nie udało się wygenerować akt. Spróbuj ponownie za chwilę.",
    pro_result_title: "Twoje akta są gotowe",
    pro_result_docnr: "Nr akt",
    pro_result_items: "Wiadomości",
    pro_result_hash: "Kod integralności (SHA-256)",
    pro_download_btn: "Pobierz akta PDF",
    pro_pdf_unavailable: "PDF niedostępny",
    pro_upsell_title: "Wciąż brak rozwiązania?",
    pro_upsell_text: "Wygeneruj profesjonalne akta przekazania, aby przekazać je prawnikowi, mediatorowi lub działowi HR. Pokazują, że próbowałeś rozwiązać sprawę wspólnie.",
    pro_upsell_btn: "Utwórz akta przekazania"
  }),
  it: createLang("Italiano", {
    tagline: "Risolvi i conflitti,",
    tagline_highlight: "senza stress.",
    sub_tagline: "Raggiungi una soluzione equa con l'aiuto dell'IA.",
    start_btn: "Avvia Mediazione (€3,99)",
    micro_time: "Intuizione media in 8–12 minuti",
    section_not_winning_title: "Vincere non è risolvere",
    section_not_winning_text: "In una lotta, nessuno vince. La mediazione si concentra sul trovare una strada da percorrere, preservare le relazioni e risparmiare tempo.",
    what_is_title: "Cos'è Rsolve?",
    what_is_p1: "Rsolve è una piattaforma de mediazione automatizzata che usa l'IA per guidare te e l'altra parte verso un accordo.",
    what_is_list_1: "Guida neutrale",
    what_is_list_2: "Soluzioni concrete",
    what_is_list_3: "Accordi chiari",
    what_is_list_4: "Accordo transattivo opzionale",
    language_title: "Funziona in ogni lingua",
    language_text: "Non lasciare che le barriere linguistiche intensifichino un conflitto. Rsolve traduce tutto istantaneamente.",
    when_title: "Ideale per...",
    when_text: "Controversie di lavoro, conflitti tra vicini, problemi di debito e disaccordi relazionali.",
    why_title: "Perché scegliere Rsolve?",
    why_1: "Nessun avvocato costoso",
    why_2: "Nessuna lunga attesa",
    why_3: "Risultati in minuti",
    why_4: "Costa solo €3,99",
    why_5: "Sicuro e confidenziale",
    why_6: "Accordi legalmente validi",
    how_title: "Come funziona",
    how_step_1: "Avvia caso",
    how_step_2: "Invita parte",
    how_step_3: "Chat guidata",
    how_step_4: "Accordo",
    faq_title: "Domande frequenti",
    footer_payoff: "Rsolve. Risolvere conflitti senza problemi.",
    footer_expats: "Adatto per espatriati e lavoratori internazionali.",
    nav_what_is: "Cos'è la mediazione?",
    nav_start: "Avvia",
    payment_title: "Pagamento unico",
    invite_header: "Invita {name}",
    vso_title: "Accordo transattivo",
    leave_modal_title: "Lasciare la mediazione?",
    vso_generating: "Stesura accordo...",
    analysing: "Il mediatore analizza...",
    typing_indicator: "sta scrivendo...",
    mediator_thinking: "Il mediatore sta pensando..."
  }),
  pt: createLang("Português", {
    tagline: "Resolva conflitos,",
    tagline_highlight: "sem complicações.",
    sub_tagline: "Cheguem a uma solução justa com a ajuda da IA.",
    start_btn: "Iniciar Mediação (€3,99)",
    micro_time: "Insight médio em 8–12 minutos",
    section_not_winning_title: "Ganhar não é resolver",
    section_not_winning_text: "Em uma briga, ninguém ganha. A mediação foca em encontrar um caminho a seguir, preservando relacionamentos e economizando tempo.",
    what_is_title: "O que é Rsolve?",
    what_is_p1: "Rsolve é uma plataforma de mediação automatizada que usa IA para guiar você e a outra parte a um acordo.",
    what_is_list_1: "Orientação neutra",
    what_is_list_2: "Soluções concretas",
    what_is_list_3: "Acordos claros",
    what_is_list_4: "Acordo de liquidação opcional",
    language_title: "Funciona em todos los idiomas",
    language_text: "Não deixe barreiras linguísticas escalarem um conflito. Rsolve traduz tudo instantaneamente.",
    when_title: "Melhor para...",
    when_text: "Disputas trabalhistas, conflitos de vizinhos, problemas de dívida e desentendimentos de relacionamento.",
    why_title: "Por que escolher Rsolve?",
    why_1: "Sem advogados caros",
    why_2: "Sem longas esperas",
    why_3: "Resultados em minutos",
    why_4: "Custa apenas €3,99",
    why_5: "Seguro e Confidencial",
    why_6: "Acordos legalmente válidos",
    how_title: "Como funciona",
    how_step_1: "Iniciar Caso",
    how_step_2: "Convidar Parte",
    how_step_3: "Chat Guiado",
    how_step_4: "Acordo",
    faq_title: "Perguntas Frequentes",
    footer_payoff: "Rsolve. Resolvendo conflitos sem problemas.",
    footer_expats: "Adequado para expatriados e trabalhadores internacionais.",
    nav_what_is: "O que é mediação?",
    nav_start: "Iniciar",
    payment_title: "Pagamento único",
    invite_header: "Convidar {name}",
    vso_title: "Acordo de liquidação",
    leave_modal_title: "Sair da mediação?",
    vso_generating: "Redigindo acordo...",
    analysing: "O mediador está analisando...",
    typing_indicator: "está digitando...",
    mediator_thinking: "Mediador pensando..."
  }),
  ro: createLang("Română", {
    tagline: "Rezolvă conflicte,",
    tagline_highlight: "fără bătăi de cap.",
    sub_tagline: "Găsiți o soluție corectă împreună cu ajutorul IA.",
    start_btn: "Începe Medierea (€3,99)",
    micro_time: "Perspectivă medie în 8–12 minute",
    section_not_winning_title: "A câștiga nu înseamnă a rezolva",
    section_not_winning_text: "Într-o luptă, nimeni nu câștigă. Medierea se concentrează pe găsirea unei căi înainte, păstrarea relațiilor și economisirea timpului.",
    what_is_title: "Ce este Rsolve?",
    what_is_p1: "Rsolve este o platformă automată de mediere care folosește IA pentru a vă ghida spre un acord.",
    what_is_list_1: "Ghidare neutră",
    what_is_list_2: "Soluții concrete",
    what_is_list_3: "Acorduri clare",
    what_is_list_4: "Acord de soluționare opțional",
    language_title: "Funcționează în orice limbă",
    language_text: "Nu lăsați barierele lingvistice să escaladeze un conflict. Rsolve traduce totul instantaneu.",
    when_title: "Cel mai bun pentru...",
    when_text: "Dispute de muncă, conflicte între vecini, probleme cu datoriile și neînțelegeri în relații.",
    why_title: "De ce să alegi Rsolve?",
    why_1: "Fără avocați scumpi",
    why_2: "Fără timpi lungi de așteptare",
    why_3: "Rezultate în minute",
    why_4: "Costă doar €3,99",
    why_5: "Sigur și Confidențial",
    why_6: "Acorduri valabile legal",
    how_title: "Cum funcționează",
    how_step_1: "Începe Caz",
    how_step_2: "Invită Parte",
    how_step_3: "Chat Ghidat",
    how_step_4: "Acord",
    faq_title: "Întrebări Frecvente",
    footer_payoff: "Rsolve. Rezolvarea conflictelor fără probleme.",
    footer_expats: "Potrivit pentru expați și lucrători internaționali.",
    nav_what_is: "Ce este medierea?",
    nav_start: "Start",
    payment_title: "Plată unică",
    invite_header: "Invită {name}",
    vso_title: "Acord de soluționare",
    leave_modal_title: "Părăsiți medierea?",
    vso_generating: "Se redactează acordul...",
    analysing: "Mediatorul analizează...",
    typing_indicator: "scrie...",
    mediator_thinking: "Mediatorul gândește..."
  }),
  bg: createLang("Български", {
    tagline: "Разрешете конфликта,",
    tagline_highlight: "без проблеми.",
    sub_tagline: "Постигнете справедливо решение с помощта на AI.",
    start_btn: "Започнете медиация (€3,99)",
    micro_time: "Средно време за прозрение 8–12 минути",
    section_not_winning_title: "Победата не е решение",
    section_not_winning_text: "В битка никой не печели. Медиацията се фокусира върху намирането на път напред и запазване на отношенията.",
    what_is_title: "Какво е Rsolve?",
    what_is_p1: "Rsolve е автоматизирана платформа за медиация, използваща AI за постигане на споразумение.",
    what_is_list_1: "Неутрално ръководство",
    what_is_list_2: "Конкретни решения",
    what_is_list_3: "Ясни споразумения",
    what_is_list_4: "Опционално споразумение",
    language_title: "Работи на всеки език",
    language_text: "Не позволявайте езиковите бариери да ескалират конфликта. Rsolve превежда всичко незабавно.",
    when_title: "Най-добро за...",
    when_text: "Трудови спорове, съседски конфликти, дългове и връзки.",
    why_title: "Защо Rsolve?",
    why_1: "Без скъпи адвокати",
    why_2: "Без чакане",
    why_3: "Резултати за минути",
    why_4: "Само €3,99",
    why_5: "Сигурно и поверително",
    why_6: "Правно валидни",
    how_title: "Как работи",
    how_step_1: "Старт",
    how_step_2: "Покана",
    how_step_3: "Чат",
    how_step_4: "Споразумение",
    faq_title: "ЧЗВ",
    footer_payoff: "Rsolve. Решаване на конфликти без проблеми.",
    footer_expats: "Подходящо за експат и чуждестранни работници.",
    nav_what_is: "Какво е медиация?",
    nav_start: "Старт",
    payment_title: "Еднократно плащане",
    invite_header: "Покани {name}",
    vso_title: "Споразумение",
    leave_modal_title: "Напускане?",
    vso_generating: "Изготвяне на споразумение...",
    analysing: "Медиаторът анализира...",
    typing_indicator: "пише...",
    mediator_thinking: "Медиаторът мисли..."
  }),
  zh: createLang("中文 (简体)", {
    tagline: "解决冲突，",
    tagline_highlight: "无忧无虑。",
    sub_tagline: "在AI调解的帮助下达成公平解决方案。",
    start_btn: "开始调解 (€3,99)",
    micro_time: "平均8-12分钟获得见解",
    section_not_winning_title: "赢不是解决之道",
    section_not_winning_text: "在争吵中，没人是赢家。调解专注于寻找前进的道路，维护关系并节省时间。",
    what_is_title: "什么是Rsolve？",
    what_is_p1: "Rsolve是一个利用人工智能引导您和对方达成协议的自动化调解平台。",
    what_is_list_1: "中立指导",
    what_is_list_2: "具体方案",
    what_is_list_3: "明确协议",
    what_is_list_4: "可选和解协议",
    language_title: "支持所有语言",
    language_text: "不要让语言障碍升级冲突。Rsolve即时翻译所有内容。",
    when_title: "适用于...",
    when_text: "劳资纠纷、邻里冲突、债务问题和关系分歧。",
    why_title: "为什么选择Rsolve？",
    why_1: "无昂贵律师费",
    why_2: "无需漫长等待",
    why_3: "几分钟见效",
    why_4: "仅需 €3.99",
    why_5: "安全保密",
    why_6: "法律有效协议",
    how_title: "工作原理",
    how_step_1: "开始案件",
    how_step_2: "邀请对方",
    how_step_3: "引导聊天",
    how_step_4: "达成协议",
    faq_title: "常见问题",
    footer_payoff: "Rsolve. 轻松解决冲突。",
    footer_expats: "适合外籍人士和国际员工。",
    nav_what_is: "什么是调解？",
    nav_start: "开始",
    payment_title: "一次性付款",
    invite_header: "邀请 {name}",
    vso_title: "和解协议",
    leave_modal_title: "离开调解？",
    vso_generating: "正在起草协议...",
    analysing: "调解员正在分析...",
    typing_indicator: "正在输入...",
    mediator_thinking: "调解员正在思考..."
  }),
  uk: createLang("Українська", {
    tagline: "Вирішуйте конфлікти,",
    tagline_highlight: "без зайвого клопоту.",
    sub_tagline: "Знайдіть справедливе рішення за допомогою ШІ.",
    start_btn: "Почати медіацію (€3,99)",
    micro_time: "Середній час розуміння 8–12 хвилин",
    section_not_winning_title: "Перемога не є вирішенням",
    section_not_winning_text: "У бійці ніхто не виграє. Медіація зосереджується на пошуку шляху вперед та збереженні стосунків.",
    what_is_title: "Що таке Rsolve?",
    what_is_p1: "Rsolve — це автоматизована платформа медіації, яка використовує ШІ для досягнення угоди.",
    what_is_list_1: "Нейтральне керівництво",
    what_is_list_2: "Конкретні рішення",
    what_is_list_3: "Чіткі угоди",
    what_is_list_4: "Опціональна мирова угода",
    language_title: "Працює будь-якою мовою",
    language_text: "Не дозволяйте мовним бар'єрам посилювати конфлікт. Rsolve перекладає все миттєво.",
    when_title: "Найкраще для...",
    when_text: "Трудових спорів, конфліктів із сусідами, боргів та стосунків.",
    why_title: "Чому Rsolve?",
    why_1: "Без дорогих юристів",
    why_2: "Без очікування",
    why_3: "Результати за хвилини",
    why_4: "Всього €3,99",
    why_5: "Безпечно та конфіденційно",
    why_6: "Юридично дійсні угоди",
    how_title: "Як це працює",
    how_step_1: "Почати",
    how_step_2: "Запросити",
    how_step_3: "Чат",
    how_step_4: "Угода",
    faq_title: "Часті запитання",
    footer_payoff: "Rsolve. Вирішення конфліктів без клопоту.",
    footer_expats: "Підходить для експатів та міжнародних працівників.",
    nav_what_is: "Що таке медіація?",
    nav_start: "Старт",
    payment_title: "Одноразовий платіж",
    invite_header: "Запросити {name}",
    vso_title: "Мирова угода",
    leave_modal_title: "Покинути медіацію?",
    vso_generating: "Складання угоди...",
    analysing: "Медіатор аналізує...",
    typing_indicator: "друкує...",
    mediator_thinking: "Медіатор думає..."
  }),
  ru: createLang("Русский", {
    tagline: "Решайте конфликты,",
    tagline_highlight: "без лишних хлопот.",
    sub_tagline: "Найдите справедливое решение с помощью ИИ.",
    start_btn: "Начать медиацию (€3,99)",
    micro_time: "Среднее время анализа 8–12 минут",
    section_not_winning_title: "Победа — это не решение",
    section_not_winning_text: "В ссоре никто не выигрывает. Медиация фокусируется на поиске пути вперед и сохранении отношений.",
    what_is_title: "Что такое Rsolve?",
    what_is_p1: "Rsolve — это автоматизированная платформа медиации, использующая ИИ для достижения соглашения.",
    what_is_list_1: "Нейтральное руководство",
    what_is_list_2: "Конкретные решения",
    what_is_list_3: "Четкие соглашения",
    what_is_list_4: "Мировое соглашение",
    language_title: "Работает на любом языке",
    language_text: "Не позволяйте языковым барьерам усугублять конфликт. Rsolve переводит все мгновенно.",
    when_title: "Лучше всего для...",
    when_text: "Трудовых споров, конфликтов с соседями, долгов и разногласий.",
    why_title: "Почему Rsolve?",
    why_1: "Без дорогих юристов",
    why_2: "Без ожидания",
    why_3: "Результаты за минуты",
    why_4: "Всего €3,99",
    why_5: "Безопасно и конфиденциально",
    why_6: "Юридически значимые",
    how_title: "Как это работает",
    how_step_1: "Начать",
    how_step_2: "Пригласить",
    how_step_3: "Чат",
    how_step_4: "Соглашение",
    faq_title: "Частые вопросы",
    footer_payoff: "Rsolve. Решение конфликтов без проблем.",
    footer_expats: "Подходит для экспатов.",
    nav_what_is: "Что такое медиация?",
    nav_start: "Старт",
    payment_title: "Единовременный платеж",
    invite_header: "Пригласить {name}",
    vso_title: "Мировое соглашение",
    leave_modal_title: "Покинуть медиацию?",
    vso_generating: "Составление соглашения...",
    analysing: "Медиатор анализирует...",
    typing_indicator: "печатает...",
    mediator_thinking: "Медиатор думает..."
  }),
  id: createLang("Bahasa Indonesia", {
    tagline: "Selesaikan konflik,",
    tagline_highlight: "tanpa repot.",
    sub_tagline: "Capai solusi adil bersama dengan bantuan mediasi AI.",
    start_btn: "Mulai Mediasi (€3,99)",
    micro_time: "Wawasan rata-rata dalam 8–12 menit",
    section_not_winning_title: "Menang bukanlah solusi",
    section_not_winning_text: "Dalam pertengkaran, tidak ada yang menang. Mediasi berfokus pada menemukan jalan ke depan dan menjaga hubungan.",
    what_is_title: "Apa itu Rsolve?",
    what_is_p1: "Rsolve adalah platform mediasi otomatis yang menggunakan AI untuk memandu Anda menuju kesepakatan.",
    what_is_list_1: "Panduan netral",
    what_is_list_2: "Solusi konkret",
    what_is_list_3: "Kesepakatan jelas",
    what_is_list_4: "Perjanjian Penyelesaian Opsional",
    language_title: "Bekerja dalam setiap bahasa",
    language_text: "Jangan biarkan hambatan bahasa memicu konflik. Rsolve menerjemahkan semuanya secara instan.",
    when_title: "Terbaik untuk...",
    when_text: "Sengketa tenaga kerja, konflik tetangga, masalah utang, dan hubungan.",
    why_title: "Mengapa memilih Rsolve?",
    why_1: "Tanpa pengacara mahal",
    why_2: "Tanpa waktu tunggu",
    why_3: "Hasil dalam hitungan menit",
    why_4: "Hanya €3,99",
    why_5: "Aman & Rahasia",
    why_6: "Sah secara hukum",
    how_title: "Cara kerja",
    how_step_1: "Mulai Kasus",
    how_step_2: "Undang Pihak",
    how_step_3: "Obrolan Terpandu",
    how_step_4: "Kesepakatan",
    faq_title: "Pertanyaan Umum",
    footer_payoff: "Rsolve. Menyelesaikan konflik tanpa repot.",
    footer_expats: "Cocok untuk ekspatriat dan pekerja internasional.",
    nav_what_is: "Apa itu mediasi?",
    nav_start: "Mulai",
    payment_title: "Pembayaran satu kali",
    invite_header: "Undang {name}",
    vso_title: "Perjanjian Penyelesaian",
    leave_modal_title: "Keluar dari mediasi?",
    vso_generating: "Menyusun perjanjian...",
    analysing: "Mediator sedang menganalisis...",
    typing_indicator: "sedang mengetik...",
    mediator_thinking: "Mediator sedang berpikir..."
  }),
  hi: createLang("हिन्दी", {
    tagline: "विवाद सुलझाएं,",
    tagline_highlight: "बिना किसी परेशानी के।",
    sub_tagline: "AI मध्यस्थता की मदद से एक निष्पक्ष समाधान तक पहुंचें।",
    start_btn: "मध्यस्थता शुरू करें (€3,99)",
    micro_time: "8-12 मिनट में औसत अंतर्दृष्टि",
    section_not_winning_title: "जीतना समाधान नहीं है",
    section_not_winning_text: "लड़ाई में कोई नहीं जीतता। मध्यस्थता आगे का रास्ता खोजने और रिश्तों को बचाने पर केंद्रित है।",
    what_is_title: "Rsolve क्या है?",
    what_is_p1: "Rsolve एक स्वचालित मध्यस्थता मंच है जो आपको समझौते तक ले जाने के लिए AI का उपयोग करता है।",
    what_is_list_1: "तटस्थ मार्गदर्शन",
    what_is_list_2: "ठोस समाधान",
    what_is_list_3: "स्पष्ट समझौते",
    what_is_list_4: "वैकल्पिक समझौता",
    language_title: "हर भाषा में काम करता है",
    language_text: "भाषा अवरोधों को संघर्ष न बढ़ने दें। Rsolve सब कुछ तुरंत अनुवाद करता है।",
    when_title: "इसके लिए सर्वश्रेष्ठ...",
    when_text: "श्रम विवाद, पड़ोसी संघर्ष, ऋण मुद्दे और संबंध।",
    why_title: "Rsolve क्यों चुनें?",
    why_1: "कोई महंगे वकील नहीं",
    why_2: "लंबा इंतजार नहीं",
    why_3: "मिनटों में परिणाम",
    why_4: "केवल €3.99",
    why_5: "सुरक्षित और गोपनीय",
    why_6: "कानूनी रूप से वैध",
    how_title: "यह कैसे काम करता है",
    how_step_1: "मामला शुरू करें",
    how_step_2: "आमंत्रित करें",
    how_step_3: "निर्देशित चैट",
    how_step_4: "समझौता",
    faq_title: "अक्सर पूछे जाने वाले प्रश्न",
    footer_payoff: "Rsolve. बिना परेशानी के संघर्ष सुलझाना।",
    footer_expats: "प्रवासियों के लिए उपयुक्त।",
    nav_what_is: "मध्यस्थता क्या है?",
    nav_start: "शुरू करें",
    payment_title: "एकमुश्त भुगतान",
    invite_header: "{name} को आमंत्रित करें",
    vso_title: "समझौता",
    leave_modal_title: "मध्यस्थता छोड़ें?",
    vso_generating: "समझौता तैयार हो रहा है...",
    analysing: "मध्यस्थ विश्लेषण कर रहा है...",
    typing_indicator: "टाइप कर रहा है...",
    mediator_thinking: "मध्यस्थ सोच रहा है..."
  }),
  ur: createLang("اردو", {
    tagline: "تنازعہ حل کریں،",
    tagline_highlight: "بغیر کسی پریشانی کے۔",
    sub_tagline: "AI ثالثی کی مدد سے منصفانہ حل تک پہنچیں۔",
    start_btn: "ثالثی شروع کریں (€3,99)",
    micro_time: "8-12 منٹ میں بصیرت",
    section_not_winning_title: "جیتنا حل نہیں ہے",
    section_not_winning_text: "لڑائی میں کوئی نہیں جیتتا۔ ثالثی آگے بڑھنے کا راستہ تلاش کرنے پر مرکوز ہے۔",
    what_is_title: "Rsolve کیا ہے؟",
    what_is_p1: "Rsolve ایک خودکار ثالثی پلیٹ فارم ہے جو AI کا استعمال کرتے ہوئے آپ کو معاہدے تک لے جاتا ہے۔",
    what_is_list_1: "غیر جانبدارانہ رہنمائی",
    what_is_list_2: "ٹھوس حل",
    what_is_list_3: "واضح معاہدے",
    what_is_list_4: "اختیاری تصفیہ معاہدہ",
    language_title: "ہر زبان میں کام کرتا ہے",
    language_text: "زبان کی رکاوٹوں کو تنازعہ نہ بڑھنے دیں۔ Rsolve فوری ترجمہ کرتا ہے۔",
    when_title: "بہترین برائے...",
    when_text: "لیبر تنازعات، پڑوسیوں کے جھگڑے، قرض کے مسائل۔",
    why_title: "Rsolve کیوں منتخب کریں؟",
    why_1: "مہنگے وکیل نہیں",
    why_2: "طویل انتظار نہیں",
    why_3: "منٹوں میں نتائج",
    why_4: "صرف €3.99",
    why_5: "محفوظ اور خفیہ",
    why_6: "قانونی طور پر درست",
    how_title: "یہ کیسے کام کرتا ہے",
    how_step_1: "کیس شروع کریں",
    how_step_2: "دعوت دیں",
    how_step_3: "گائیڈڈ چیٹ",
    how_step_4: "معاہدہ",
    faq_title: "عام سوالات",
    footer_payoff: "Rsolve. تنازعہ کا آسان حل۔",
    footer_expats: "تارکین وطن کے لیے موزوں۔",
    nav_what_is: "ثالثی کیا ہے؟",
    nav_start: "شروع کریں",
    payment_title: "ایک بار ادائیگی",
    invite_header: "{name} کو مدعو کریں",
    vso_title: "تصفیہ کا معاہدہ",
    leave_modal_title: "ثالثی چھوڑ دیں؟",
    vso_generating: "معاہدہ تیار ہو رہا ہے...",
    analysing: "ثالث تجزیہ کر رہا ہے...",
    typing_indicator: "لکھ رہا ہے...",
    mediator_thinking: "ثالث سوچ رہا ہے..."
  }),
  fa: createLang("فارسی", {
    tagline: "حل اختلاف،",
    tagline_highlight: "بدون دردسر.",
    sub_tagline: "با کمک میانجیگری هوش مصنوعی به یک راه حل عادلانه برسید.",
    start_btn: "شروع میانجیگری (€3,99)",
    micro_time: "بینش متوسط در ۸-۱۲ دقیقه",
    section_not_winning_title: "برنده شدن راه حل نیست",
    section_not_winning_text: "در دعوا هیچکس برنده نیست. میانجیگری بر یافتن راهی به جلو و حفظ روابط تمرکز دارد.",
    what_is_title: "Rsolve چیست؟",
    what_is_p1: "Rsolve یک پلتفرم میانجیگری خودکار است که از هوش مصنوعی برای راهنمایی شما به سمت توافق استفاده می‌کند.",
    what_is_list_1: "راهنمایی بی طرف",
    what_is_list_2: "راه حل های ملموس",
    what_is_list_3: "توافقات روشن",
    what_is_list_4: "توافقنامه تسویه حساب اختیاری",
    language_title: "در هر زبانی کار می کند",
    language_text: "اجازه ندهید موانع زبانی درگیری را تشدید کنند. Rsolve همه چیز را فوراً ترجمه می کند.",
    when_title: "بهترین برای...",
    when_text: "اختلافات کاری، درگیری همسایگان، مسائل بدهی و روابط.",
    why_title: "چرا Rsolve؟",
    why_1: "بدون وکیل گران",
    why_2: "بدون انتظار طولانی",
    why_3: "نتائج در چند دقیقه",
    why_4: "فقط €3.99",
    why_5: "امن و محرمانه",
    why_6: "توافقات قانونی معتبر",
    how_title: "چگونه کار می کند",
    how_step_1: "شروع پرونده",
    how_step_2: "دعوت",
    how_step_3: "چت هدایت شده",
    how_step_4: "توافق",
    faq_title: "سوالات متداول",
    footer_payoff: "Rsolve. حل اختلاف بدون دردسر.",
    footer_expats: "مناسب برای مهاجران.",
    nav_what_is: "میانجیگری چیست؟",
    nav_start: "شروع",
    payment_title: "پرداخت یکجا",
    invite_header: "دعوت از {name}",
    vso_title: "توافقنامه تسویه حساب",
    leave_modal_title: "ترک میانجیگری؟",
    vso_generating: "در حال پیش‌نویس توافق...",
    analysing: "میانجی در حال تجزیه و تحلیل...",
    typing_indicator: "در حال تایپ...",
    mediator_thinking: "میانجی در حال فکر کردن..."
  }),
  ku: createLang("Kurdî", {
    tagline: "Nakokiyê çareser bikin,",
    tagline_highlight: "bêyî alozî.",
    sub_tagline: "Bi alîkariya navbeynkariya AI bigihîjin çareseriyek dadperwer.",
    start_btn: "Navbeynkariyê dest pê bikin (€3,99)",
    micro_time: "Di 8-12 deqeyan de têgihiştin",
    section_not_winning_title: "Serkeftin ne çareserî ye",
    section_not_winning_text: "Di şer de kes bi ser nakeve. Navbeynkarî li ser dîtina rêyek pêş de disekine.",
    what_is_title: "Rsolve çi ye?",
    what_is_p1: "Rsolve platformek navbeynkariya otomatîk e ku AI bikar tîne da ku bigihîje peymanekê.",
    what_is_list_1: "Rêbernameya bêalî",
    what_is_list_2: "Çareseriyên şênber",
    what_is_list_3: "Peymanên zelal",
    what_is_list_4: "Peymana lihevkirinê",
    language_title: "Bi her zimanî dixebite",
    language_text: "Astengên ziman nehêlin nakokî zêde bibe. Rsolve her tiştî wergerîne.",
    when_title: "Baştirîn ji bo...",
    when_text: "Nakokiyên kar, cîran, deyn û têkiliyan.",
    why_title: "Çima Rsolve?",
    why_1: "Bê parêzerên biha",
    why_2: "Bê li bendê",
    why_3: "Encam di deqeyan de",
    why_4: "Tenê €3,99",
    why_5: "Ewle û Veşartî",
    why_6: "Peymanên qanûnî",
    how_title: "Çawa dixebite",
    how_step_1: "Destpêk",
    how_step_2: "Vexwendin",
    how_step_3: "Chat",
    how_step_4: "Peyman",
    faq_title: "Pirsên Pir tên Pirsîn",
    footer_payoff: "Rsolve. Çareserkirina nakokiyan.",
    footer_expats: "Ji bo koçberan maqûl e.",
    nav_what_is: "Navbeynkarî çi ye?",
    nav_start: "Destpêk",
    payment_title: "Tezmînata yekcar",
    invite_header: "{name} vexwendin",
    vso_title: "Peymana lihevkirinê",
    leave_modal_title: "Jê derkeve?",
    vso_generating: "Peyman tê amadekirin...",
    analysing: "Navbeynkar analîz dike...",
    typing_indicator: "dinivîse...",
    mediator_thinking: "Navbeynkar difikire..."
  }),
  el: createLang("Ελληνικά", {
    tagline: "Λύστε τη σύγκρουση,",
    tagline_highlight: "χωρίς ταλαιπωρία.",
    sub_tagline: "Βρείτε μια δίκαιη λύση μαζί με τη βοήθεια της AI.",
    start_btn: "Έναρξη Διαμεσολάβησης (€3,99)",
    micro_time: "Μέση εικόνα σε 8–12 λεπτά",
    section_not_winning_title: "Η νίκη δεν είναι λύση",
    section_not_winning_text: "Σε έναν καβγά, κανείς δεν κερδίζει. Η διαμεσολάβηση εστιάζει στην εύρεση μιας λύσης και στη διατήρηση των σχέσεων.",
    what_is_title: "Τι είναι το Rsolve?",
    what_is_p1: "Το Rsolve είναι μια αυτοματοποιημένη πλατφόρμα διαμεσολάβησης που χρησιμοποιεί AI για να σας οδηγήσει σε συμφωνία.",
    what_is_list_1: "Ουδέτερη καθοδήγηση",
    what_is_list_2: "Συγκεκριμένες λύσεις",
    what_is_list_3: "Ξεκάθαρες συμφωνίες",
    what_is_list_4: "Προαιρετική Συμφωνία Συμβιβασμού",
    language_title: "Λειτουργεί σε κάθε γλώσσα",
    language_text: "Μην αφήνετε τα γλωσσικά εμπόδια να κλιμακώσουν μια σύγκρουση. Το Rsolve μεταφράζει τα πάντα άμεσα.",
    when_title: "Καλύτερο για...",
    when_text: "Εργατικές διαφορές, συγκρούσεις γειτόνων, ζητήματα χρέους και διαφωνίες σχέσεων.",
    why_title: "Γιατί Rsolve;",
    why_1: "Χωρίς ακριβούς δικηγόρους",
    why_2: "Χωρίς αναμονή",
    why_3: "Αποτελέσματα σε λεπτά",
    why_4: "Μόνο €3,99",
    why_5: "Ασφαλές & Εμπιστευτικό",
    why_6: "Νομικά έγκυρες συμφωνίες",
    how_title: "Πώς λειτουργεί",
    how_step_1: "Έναρξη",
    how_step_2: "Πρόσκληση",
    how_step_3: "Συζήτηση",
    how_step_4: "Συμφωνία",
    faq_title: "Συχνές Ερωτήσεις",
    footer_payoff: "Rsolve. Επίλυση συγκρούσεων χωρίς κόπο.",
    footer_expats: "Κατάλληλο για ομογενείς.",
    nav_what_is: "Τι είναι η διαμεσολάβηση;",
    nav_start: "Έναρξη",
    payment_title: "Εφάπαξ πληρωμή",
    invite_header: "Πρόσκληση {name}",
    vso_title: "Συμφωνία συμβιβασμού",
    leave_modal_title: "Αποχώρηση;",
    vso_generating: "Σύνταξη συμφωνίας...",
    analysing: "Ο διαμεσολαβητής αναλύει...",
    typing_indicator: "πληκτρολογεί...",
    mediator_thinking: "Ο διαμεσολαβητής σκέφτεται..."
  }),
  hu: createLang("Magyar", {
    tagline: "Oldja meg a konfliktust,",
    tagline_highlight: "zökkenőmentesen.",
    sub_tagline: "Találjanak közös, igazságos megoldást az AI segítségével.",
    start_btn: "Mediáció indítása (€3,99)",
    micro_time: "Átlagos betekintés 8–12 perc alatt",
    section_not_winning_title: "A győzelem nem megoldás",
    section_not_winning_text: "Egy veszekedésben senki sem nyer. A mediáció a megoldás megtalálására és a kapcsolatok megőrzésére összpontosít.",
    what_is_title: "Mi az Rsolve?",
    what_is_p1: "Az Rsolve egy automatizált mediációs platform, amely AI-t használ a megállapodás eléréséhez.",
    what_is_list_1: "Semleges útmutatás",
    what_is_list_2: "Konkrét megoldások",
    what_is_list_3: "Világos megállapodások",
    what_is_list_4: "Opcionális egyezségi megállapodás",
    language_title: "Minden nyelven működik",
    language_text: "Ne hagyja, hogy a nyelvi akadályok fokozzák a konfliktust. Az Rsolve mindent azonnal lefordít.",
    when_title: "A legjobb...",
    when_text: "Munkaügyi viták, szomszédi konfliktusok, adósságügyek és párkapcsolati nézeteltérések.",
    why_title: "Miért az Rsolve?",
    why_1: "Nincsenek drága ügyvédek",
    why_2: "Nincs várakozási idő",
    why_3: "Eredmények percek alatt",
    why_4: "Csak €3,99",
    why_5: "Biztonságos és bizalmas",
    why_6: "Jogilag érvényes",
    how_title: "Hogyan működik",
    how_step_1: "Indítás",
    how_step_2: "Meghívás",
    how_step_3: "Chat",
    how_step_4: "Megállapodás",
    faq_title: "Gyakori kérdések",
    footer_payoff: "Rsolve. Konfliktuskezelés gond nélkül.",
    footer_expats: "Alkalmas külföldiek számára.",
    nav_what_is: "Mi a mediáció?",
    nav_start: "Indítás",
    payment_title: "Egyszeri fizetés",
    invite_header: "{name} meghívása",
    vso_title: "Egyezségi megállapodás",
    leave_modal_title: "Kilépés?",
    vso_generating: "Megállapodás készítése...",
    analysing: "A mediátor elemez...",
    typing_indicator: "gépel...",
    mediator_thinking: "A mediátor gondolkodik..."
  }),
};
