
import React from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { ICONS } from '../constants';

const CaseAgreement: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams();

  return (
    <div className="p-6 flex flex-col min-h-screen bg-white">
      <header className="mb-8">
        <h1 className="text-2xl font-bold text-slate-900">Final Agreement</h1>
        <p className="text-sm text-slate-500 mt-1">Legally binding resolution summary</p>
      </header>

      <Card className="flex-1 bg-slate-50 border-dashed border-2 mb-8 p-6 overflow-y-auto">
        <div className="prose prose-sm text-slate-700">
          <h3 className="text-lg font-black text-slate-900 mb-4">SETTLEMENT CONTRACT</h3>
          <p className="text-xs leading-relaxed mb-4">
            This agreement is entered into between **Jordan Peterson** (the "Initiator") and **Alex Smith** (the "Respondent") regarding the dispute: **Property Damage - Unit 4B**.
          </p>
          <div className="space-y-4">
            <div className="bg-white p-4 rounded-lg shadow-sm border border-slate-200">
              <h4 className="text-[10px] font-black uppercase tracking-widest text-blue-600 mb-2">Resolution Terms</h4>
              <p className="text-sm font-bold">1. Financial Settlement</p>
              <p className="text-xs text-slate-600">The Respondent agrees to pay the Initiator the sum of **$450.00** via Rsolve Secure Pay.</p>
              <p className="text-sm font-bold mt-3">2. Mutual Release</p>
              <p className="text-xs text-slate-600">Both parties agree to release each other from any further liability regarding this specific incident.</p>
            </div>
            
            <p className="text-[10px] text-slate-400 italic">
              Electronically generated by Rsolve AI Mediation Engine. 
              Certified compliant with standard arbitration protocols.
            </p>
          </div>
        </div>
      </Card>

      <div className="space-y-4">
        <div className="flex items-start gap-3 p-4 bg-emerald-50 rounded-xl">
           <ICONS.Check className="text-emerald-500 shrink-0 mt-0.5" />
           <p className="text-xs font-medium text-emerald-800">By tapping 'Sign Agreement', you confirm you have read and accepted these terms in full.</p>
        </div>
        <div className="grid grid-cols-2 gap-3">
          <Button variant="outline" size="lg" onClick={() => navigate(`/cases/${id}/proposals`)}>Back</Button>
          <Button size="lg" onClick={() => navigate('/dashboard')}>Sign Agreement</Button>
        </div>
      </div>
    </div>
  );
};

export default CaseAgreement;
